#!/usr/bin/env python3
"""Generate godot/data/lore.json and docs/LORE.md from the authored data in tools/specs/lore_data.py.

    python tools/specs/gen_lore.py [--root DIR]

Derived values (lane distances, ETAs, ship position) are computed here so they are always consistent.  Standard library only,
deterministic (no timestamps).
"""
import argparse
import heapq
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import lore_data as L  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))


def dist(a, b):
    return math.sqrt(sum((x - y) ** 2 for x, y in zip(a, b)))


def shortest_path(routes, a, b):
    """Dijkstra on lane distance; returns (ly, [system ids])."""
    adj = {}
    for r in routes:
        adj.setdefault(r["a"], []).append((r["b"], r["ly"]))
        adj.setdefault(r["b"], []).append((r["a"], r["ly"]))
    best = {a: 0.0}
    prev = {}
    heap = [(0.0, a)]
    while heap:
        d, u = heapq.heappop(heap)
        if d > best.get(u, 1e18):
            continue
        if u == b:
            break
        for v, w in sorted(adj.get(u, [])):
            nd = d + w
            if nd < best.get(v, 1e18) - 1e-12:
                best[v] = nd
                prev[v] = u
                heapq.heappush(heap, (nd, v))
    if b not in best:
        return None, []
    path = [b]
    while path[-1] != a:
        path.append(prev[path[-1]])
    return best[b], path[::-1]


def build():
    ship = dict(L.SHIP)
    pos = {s[0]: s[2] for s in L.SYSTEMS}
    systems = []
    for sid, name, p, (cls, temp, lum), fac, kind, visited, summary, planets in L.SYSTEMS:
        systems.append({"id": sid, "name": name, "pos": [round(v, 2) for v in p],
                        "star": {"class": cls, "temp_k": temp, "lum_solar": lum}, "faction": fac, "kind": kind,
                        "visited": visited, "summary": summary, "planets": planets})
    routes = []
    for a, b, hz in L.ROUTES:
        routes.append({"a": a, "b": b, "ly": round(dist(pos[a], pos[b]), 2), "hazard": hz})
    speed = ship["ly_per_day_at_cruise"]
    wps = []
    prev = None
    for sysid, objective, survey, status in L.WAYPOINTS:
        if prev is None:
            ly, via = 0.0, [sysid]
        else:
            ly, via = shortest_path(routes, prev, sysid)
        wps.append({"system": sysid, "objective": objective, "eta_days": round(ly / speed, 2), "status": status,
                    "from": prev or "", "leg_ly": round(ly, 2), "via": via, "survey_days": survey})
        prev = sysid
    cur = L.CURRENT
    cp, tp = pos[cur["system"]], pos[cur["toward"]]
    d = dist(cp, tp)
    heading = [round((t - c) / d, 3) for c, t in zip(cp, tp)]
    current = {"system": cur["system"], "status": cur["status"], "heading": heading, "toward": cur["toward"]}
    return {
        "version": 1,
        "ship": ship,
        "factions": [{"id": i, "name": n, "color": c, "stance": st, "description": d_} for i, n, c, st, d_ in L.FACTIONS],
        "systems": systems,
        "routes": routes,
        "waypoints": wps,
        "current": current,
        "timeline": [{"year": y, "title": t, "text": x} for y, t, x in L.TIMELINE],
        "logs": [{"stardate": sd, "role": r, "author": au, "title": t, "text": x, "room": rm} for sd, r, au, t, x, rm in L.LOGS],
        "datapads": [{"id": i, "title": t, "text": x} for i, t, x in L.DATAPADS],
        "glossary": [{"term": t, "text": x} for t, x in L.GLOSSARY],
    }


def esc(s):
    return str(s).replace("|", "\\|")


def markdown(d):
    out = []
    w = out.append
    ship = d["ship"]
    sysname = {s["id"]: s["name"] for s in d["systems"]}
    facname = {f["id"]: f["name"] for f in d["factions"]}
    w("# StarshipGo - Lore: the voyage of the %s" % ship["name"])
    w("")
    w("*Generated by `python tools/specs/gen_lore.py` from `tools/specs/lore_data.py`; do not edit by hand. The game reads "
      "[`godot/data/lore.json`](../godot/data/lore.json) (star map, logs, datapads).*")
    w("")
    w("## 1. The ship")
    w("")
    w(ship["description"])
    w("")
    w("| | |")
    w("|---|---|")
    for k, lab in [("name", "Name"), ("registry", "Registry"), ("class", "Class"), ("builder", "Builder"), ("commissioned", "Commissioned"),
                   ("motto", "Motto"), ("crew", "Crew complement"), ("cruise_warp", "Cruise speed (warp factor)"), ("top_warp", "Top speed (warp factor)"),
                   ("ly_per_day_at_cruise", "Distance per day at cruise (ly)"), ("charter", "Charter")]:
        w("| %s | %s |" % (lab, esc(ship[k])))
    w("")
    w("## 2. Powers of the volume")
    w("")
    w("| Faction | Colour | Stance | Systems | About |")
    w("|---|---|---|---|---|")
    for f in d["factions"]:
        n = sum(1 for s in d["systems"] if s["faction"] == f["id"])
        w("| %s | `%s` | %s | %d | %s |" % (f["name"], f["color"], f["stance"], n, esc(f["description"])))
    w("")
    w("## 3. Star map")
    w("")
    w("%d systems within about %.0f light-years of Tessara, joined by %d lanes (distance in light-years). Coordinates are light-years from Tessara." % (
        len(d["systems"]), max(math.sqrt(sum(c * c for c in s["pos"])) for s in d["systems"]), len(d["routes"])))
    w("")
    w("```mermaid")
    w("flowchart LR")
    for s in d["systems"]:
        shape = {"home": '(["%s"])', "anomaly": '{{"%s"}}', "hazard": '>"%s"]', "uncharted": '("%s")'}.get(s["kind"], '["%s"]')
        w("    %s%s" % (s["id"], shape % (s["name"] + ("<br/>" + s["star"]["class"]))))
    for r in sorted(d["routes"], key=lambda r: (r["a"], r["b"])):
        w("    %s %s|%.1f ly| %s" % (r["a"], "-.-" if r["hazard"] >= 3 else "---", r["ly"], r["b"]))
    for f in d["factions"]:
        ids = [s["id"] for s in d["systems"] if s["faction"] == f["id"]]
        if ids:
            w("    style %s fill:%s,color:#000" % (",".join(ids), f["color"]))
    w("```")
    w("")
    w("Dotted lanes have hazard 3 or more. The **current position** is %s; the mission plan runs through the systems below." % sysname[d["current"]["system"]])
    w("")
    w("### 3.1 Systems")
    w("")
    w("| System | Faction | Kind | Star | Position (ly) | Planets | Visited |")
    w("|---|---|---|---|---|---|---|")
    for s in d["systems"]:
        st = s["star"]
        w("| %s | %s | %s | %s, %d K, %g L | %s | %d | %s |" % (s["name"], facname[s["faction"]], s["kind"], st["class"], st["temp_k"], st["lum_solar"],
                                                              ", ".join("%.1f" % v for v in s["pos"]), len(s["planets"]), "yes" if s["visited"] else "no"))
    w("")
    w("### 3.2 Planets and notes")
    w("")
    for s in d["systems"]:
        w("**%s** - %s" % (s["name"], s["summary"]))
        w("")
        w("| Planet | Type | Gravity | Atmosphere | Habitable | Moons | Notes |")
        w("|---|---|---|---|---|---|---|")
        for p in s["planets"]:
            w("| %s | %s | %.2f g | %s | %s | %d | %s |" % (p["name"], p["type"], p["gravity_g"], p["atmosphere"], "yes" if p["habitable"] else "no", p["moons"], esc(p["notes"])))
        w("")
    w("### 3.3 Lanes")
    w("")
    w("| From | To | Distance (ly) | Hazard (0-5) | Days at cruise |")
    w("|---|---|---|---|---|")
    for r in sorted(d["routes"], key=lambda r: (r["a"], r["b"])):
        w("| %s | %s | %.2f | %d | %.1f |" % (sysname[r["a"]], sysname[r["b"]], r["ly"], r["hazard"], r["ly"] / ship["ly_per_day_at_cruise"]))
    w("")
    w("## 4. Mission plan")
    w("")
    w("Travel time is the shortest lane path between consecutive waypoints divided by the cruise speed (%.2f ly per day, warp %g). Survey time is spent in the system." % (
        ship["ly_per_day_at_cruise"], ship["cruise_warp"]))
    w("")
    w("| # | Waypoint | Status | Leg (ly) | Travel (days) | Survey (days) | Objective |")
    w("|---|---|---|---|---|---|---|")
    tot_t = tot_s = 0.0
    for i, wp in enumerate(d["waypoints"], 1):
        tot_t += wp["eta_days"]
        tot_s += wp["survey_days"]
        w("| %d | %s | %s | %.2f | %.2f | %d | %s |" % (i, sysname[wp["system"]], wp["status"], wp["leg_ly"], wp["eta_days"], wp["survey_days"], esc(wp["objective"])))
    w("")
    w("Total travel %.1f days, survey %d days; the rest of the four-year charter is reserve for the Lighthouse." % (tot_t, tot_s))
    w("")
    w("**Current position:** %s - %s" % (sysname[d["current"]["system"]], d["current"]["status"]))
    w("")
    w("## 5. Timeline")
    w("")
    w("| Year (CY) | Event | |")
    w("|---|---|---|")
    for t in d["timeline"]:
        w("| %d | **%s** | %s |" % (t["year"], t["title"], esc(t["text"])))
    w("")
    w("## 6. Ship's log - the story so far")
    w("")
    w("%d entries, from departure (stardate 41000.0) to the present. Rooms refer to the ship's room ids (see [SHIP_SPEC](SHIP_SPEC.md))." % len(d["logs"]))
    w("")
    for l in d["logs"]:
        w("### %s - %s" % (l["stardate"], l["title"]))
        w("")
        w("*%s (%s)%s*" % (l["author"], l["role"], (", at `%s`" % l["room"]) if l["room"] else ""))
        w("")
        w(l["text"])
        w("")
    w("## 7. Datapads")
    w("")
    for p in d["datapads"]:
        w("### %s" % p["title"])
        w("")
        w(p["text"])
        w("")
    w("## 8. Glossary")
    w("")
    w("| Term | Meaning |")
    w("|---|---|")
    for g in d["glossary"]:
        w("| %s | %s |" % (g["term"], esc(g["text"])))
    w("")
    return "\n".join(out) + "\n"


def write_all(root, json_path=None, md_path=None):
    d = build()
    jp = json_path or os.path.join(root, "godot", "data", "lore.json")
    mp = md_path or os.path.join(root, "docs", "LORE.md")
    for p in (jp, mp):
        os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(jp, "w") as f:
        json.dump(d, f, indent=1)
        f.write("\n")
    with open(mp, "w") as f:
        f.write(markdown(d))
    return jp, mp


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=ROOT)
    ap.add_argument("--json", default=None)
    ap.add_argument("--md", default=None)
    a = ap.parse_args()
    jp, mp = write_all(a.root, a.json, a.md)
    print("wrote", jp, mp)


if __name__ == "__main__":
    main()
