#!/usr/bin/env python3
"""Generate docs/SOFTWARE_SPEC.md and godot/data/software.json from tools/specs/software_data.py.

    python tools/specs/gen_software.py [--root DIR]

Pure standard library and deterministic (no timestamps).
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import software_data as sd  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
VERSION = "1.0"


def software_json():
    apps = []
    for a in sd.APPS:
        apps.append({"id": a["id"], "title": a["title"], "version": VERSION, "category": a["category"], "description": a["purpose"],
                     "screen_textures": list(a["textures"]), "categories": list(a["hosts"]), "rooms": list(a["rooms"]),
                     "hosts": list(a["hosts"]), "update_rate": a["rate"]})
    return {"version": 1, "fallback": "computer", "theme": sd.THEME,
            "categories": [{"id": i, "title": t} for i, t in sd.CATEGORIES],
            "apps": apps,
            "texture_map": dict(sorted(sd.TEXTURE_MAP.items())),
            "texture_prefix_map": dict(sorted(sd.TEXTURE_PREFIX_MAP.items())),
            "category_map": dict(sorted(sd.CATEGORY_APP.items()))}


def bullets(w, items):
    for i in items:
        w("* %s" % i)
    w("")


def app_section(w, n, a):
    w("### 4.%d `%s` - %s" % (n, a["id"], a["title"]))
    w("")
    w("**Category** %s | **Version** %s | **Update rate** %s" % (a["category"], VERSION, a["rate"]))
    w("")
    w("**Purpose.** %s" % a["purpose"])
    w("")
    w("**Who uses it.** %s" % a["users"])
    w("")
    w("**Hosted by.** Rooms (hints, the ids may change with the layout): %s. Machine categories: %s. Screen textures that open it: %s." % (
        ", ".join("`%s`" % r for r in a["rooms"]), ", ".join("`%s`" % h for h in a["hosts"]),
        ", ".join("`%s`" % t for t in a["textures"]) if a["textures"] else "none of its own (opened by category / prefix rules, see 3.2)"))
    w("")
    w("**Layout (1280x720 logical, wireframe)**")
    w("")
    w("```text")
    w(a["wireframe"])
    w("```")
    w("")
    w("**Widgets**")
    w("")
    bullets(w, a["widgets"])
    w("**Data sources**")
    w("")
    bullets(w, a["data"])
    w("**Interactions and keys** (plus the common keys of section 2)")
    w("")
    bullets(w, a["interactions"])
    w("**Alarms and error states**")
    w("")
    bullets(w, a["alarms"])
    w("**Effects on the game world** (through the shared `ShipState`)")
    w("")
    bullets(w, a["effects"])
    w("**Performance budget.** %s Update rate: %s Only the open app runs; the screen texture of the machine stays static while an app is open elsewhere." % (a["perf"], a["rate"]))
    w("")
    w("**Accessibility.** Every colour state also has a text or shape cue (OK / WARN / CRIT chips with icons); all actions are reachable with the keyboard; text is at least 18 px at 1280x720; `Settings.reduce_motion` stops sweeps and blinking; sounds have on-screen text equivalents.")
    w("")
    for title, items in a["extra"]:
        w("**%s**" % title)
        w("")
        bullets(w, items)
    w("**Acceptance tests**")
    w("")
    for i, t in enumerate(a["accept"], 1):
        w("%d. %s" % (i, t))
    w("")


def generate():
    out = []
    w = out.append
    ids = [a["id"] for a in sd.APPS]
    w("# StarshipGo - Software Specification")
    w("")
    w("*Generated by `python tools/specs/gen_software.py` from `tools/specs/software_data.py`; do not edit by hand. "
      "Machine-readable form: [`godot/data/software.json`](../godot/data/software.json).*")
    w("")
    w("Every screen on the ship is interactive. Walk up to any screen, press **E**, and a full-screen terminal opens running one of the %d "
      "**applications** below. This document is the specification the Godot implementation follows: what each application shows, which "
      "data it reads, what it changes in the world and how it is tested. The star map and the logs read [`lore.json`](../godot/data/lore.json) "
      "([lore](LORE.md)), the machine cards read [`specs.json`](../godot/data/specs.json) ([datasheets](MACHINE_SPECS.md)), the deck plan "
      "reads `ship.json` ([ship spec](SHIP_SPEC.md))." % len(ids))
    w("")
    w("## Contents")
    w("")
    w("1. Overview and application catalogue")
    w("2. Cross-cutting: visual language, input model, shared state, persistence, schemas, errors, versioning, performance")
    w("3. Mapping screens to applications (textures, prefixes, categories)")
    w("4. The applications")
    w("5. QA matrix and glossary")
    w("")
    w("## 1. Application catalogue")
    w("")
    w("| Id | Title | Category | Opens from textures | Typical rooms | Update rate |")
    w("|---|---|---|---|---|---|")
    for a in sd.APPS:
        w("| `%s` | %s | %s | %s | %s | %s |" % (a["id"], a["title"], a["category"], ", ".join(a["textures"]) or "-",
                                                  ", ".join(a["rooms"][:4]), a["rate"].split(";")[0].rstrip(".")))
    w("")
    w("```mermaid")
    w("flowchart LR")
    w("    E[Player presses E on a screen] --> R[ScreenRegistry: texture -> app id]")
    w("    R --> A[Terminal overlay runs the application]")
    w("    A <--> S[(ShipState autoload)]")
    w("    S --> W[World: lights, doors, hangar field, power, destination]")
    w("    L[lore.json] --> A")
    w("    P[specs.json] --> A")
    w("    H[ship.json] --> A")
    w("```")
    w("")
    w("## 2. Cross-cutting specification")
    w("")
    w("### 2.1 Visual language")
    w("")
    w("An original, calm instrument look: dark blue-black glass, thin cyan linework, generous spacing, rounded 6 px panels and no franchise iconography.")
    w("")
    w("| Token | Colour | Use |")
    w("|---|---|---|")
    for k, v in sd.THEME.items():
        w("| `%s` | `%s` | %s |" % (k, v, {"bg": "terminal background", "panel": "panel fill", "panel_hi": "focused / hovered panel", "line": "borders, grid lines",
                                            "text": "primary text", "dim": "secondary text, disabled", "accent": "titles, selection, links", "accent2": "highlights, lore signal",
                                            "ok": "nominal state", "warn": "caution state", "crit": "fault state", "info": "notices",
                                            "alert_green": "alert level green", "alert_yellow": "alert level yellow", "alert_red": "alert level red"}[k]))
    w("")
    bullets(w, ["**Fonts.** One monospace font for numbers and terminals (bundled, SIL OFL licence, e.g. a DejaVu Sans Mono or JetBrains Mono class font; fallback: Godot's default) and one sans for labels. Sizes: title 28 px, body 20 px, small 16 px (never smaller) at the 1280x720 logical resolution.",
                "**Spacing.** 8 px grid; panel padding 12 px; widget gap 8 px; 2 px focus ring in `accent`.",
                "**Frame.** Every app has a 40 px title bar (app title, ship stardate, alert chip) and a 28 px key hint footer.",
                "**Motion.** Fades 120 ms, sweeps and traces 30 Hz at most; no flashing faster than 3 Hz.",
                "**Sound.** Click, confirm, error and alarm cues; each is optional and has a text twin."])
    w("### 2.2 Input model")
    w("")
    bullets(w, ["**E** (or the use action) while looking at a screen within 2.5 m opens the terminal; the player is frozen and the mouse is released. A prompt \"E - use <app title>\" appears when a screen is in reach.",
                "**Esc** closes the terminal and restores the mouse capture; `Tab`/`Shift+Tab` move focus; arrow keys move selection; `Enter` activates; `Space` toggles; `PageUp`/`PageDown` scroll; mouse click, wheel and drag are always supported; gamepad is out of scope.",
                "Only one terminal can be open. Opening is blocked while a fade or a stair transition is running. All shortcuts are listed in the footer of each app.",
                "Text entry fields capture all keys except `Esc` and `Tab`."])
    w("### 2.3 Shared state (`ShipState` autoload)")
    w("")
    w("One autoload holds every value that applications read or write; signals notify the world. Applications never reach into the scene tree.")
    w("")
    w("| Field | Type | Default | Written by | Effect |")
    w("|---|---|---|---|---|")
    for row in [
        ("alert", "int 0/1/2 (green/yellow/red)", "0", "alert, tactical, computer", "room lights tint; red locks brig and armory"),
        ("door_locks", "Dictionary door_index -> bool", "armory and brig locked", "security, computer", "locked doors do not open; red status light"),
        ("deck_power", "Array bool per deck", "all true", "power", "deck lights off when false"),
        ("power", "supply_mw, load_mw, battery_mwh, shed bool", "from SHIP_SPEC", "power, reactor, warp", "lighting 50 % when shed"),
        ("reactor", "running, output_pct, fuel, containment", "running 72 %", "reactor", "supply; SCRAM -> battery"),
        ("warp", "online, engaged, factor, field", "online false", "warp, nav, starmap", "enables jump, speed"),
        ("throttle", "float 0..top_warp", "0", "nav", "speed and ETA"),
        ("destination", "system id or empty", "next waypoint", "starmap, nav, computer", "course and ETA"),
        ("route", "Array of system ids", "[]", "starmap", "multi-hop plan"),
        ("position_system", "system id", "lore.current.system", "game (arrival)", "chart marker"),
        ("shields", "on, quadrants[4]", "off", "tactical", "none visual"),
        ("hangar", "field_on, door_state", "field on, closed", "docking", "force-field node visible"),
        ("atmosphere", "per deck o2, co2, temp, kpa", "nominal", "lifesupport", "alarms"),
        ("systems", "name -> health 0..100; faults[]", "2-4 minor faults", "engineering, diagnostics", "alarms"),
        ("log / messages", "arrays", "from lore.json", "science, comms", "logbook, comms"),
        ("clock", "stardate, ship seconds", "lore.current + 0", "game loop", "chronometer"),
        ("credits", "int", "120", "vending, galley", "purchases"),
        ("cargo", "stores dictionary", "from SHIP_SPEC", "cargo, fabricator, galley, hydroponics", "manifest"),
        ("read_pads", "set of datapad ids", "empty", "datapad", "none"),
        ("settings", "reduce_motion, volume, clock_24h", "false, 1.0, true", "all", "accessibility")]:
        w("| `%s` | %s | %s | %s | %s |" % row)
    w("")
    w("### 2.4 Persistence")
    w("")
    bullets(w, ["Saved to `user://shipstate.json` when a terminal closes and on quit (atomic write: temp file then rename). Keys: the fields above plus `schema` (int) and `saved_at` (OS clock; the only non-deterministic field and never written to the repo).",
                "Missing or corrupt save: defaults are used and a one-line warning is logged. Unknown keys are kept and re-saved (forward compatibility).",
                "Persistence of `settings` is separate (`user://settings.cfg`)."])
    w("### 2.5 Data schemas and versioning")
    w("")
    bullets(w, ["`lore.json`, `specs.json`, `software.json` each carry `\"version\": 1`. Applications check the major version and show `DATA VERSION MISMATCH` (crit) if higher than supported; extra keys are ignored.",
                "Application semantic versions (`software.json` `apps[].version`) are shown in the footer; changes to a ShipState field name bump the minor version of every app that touches it.",
                "Compact keys of `specs.json` are documented in [MACHINE_SPECS.md](MACHINE_SPECS.md). A model missing from `specs.json` renders `-` placeholders, never an error."])
    w("### 2.6 Error handling")
    w("")
    bullets(w, ["Missing data file: the app opens with an in-world error screen (\"DATA LINK DOWN\") listing the file name; the game never crashes.",
                "Unknown screen texture: the `computer` app opens.",
                "Any script error inside an app closes it to the world with a toast; the error is logged with the app id.",
                "Every numeric widget clamps its input; every list handles zero rows with an empty-state message."])
    w("### 2.7 Performance budget (all apps)")
    w("")
    bullets(w, ["The terminal is a `CanvasLayer` with Control nodes; at most one `SubViewport` per app (starmap, holo, camera tiles).",
                "Script time per frame < 1 ms; zero allocations in `_process` hot paths; the world stays rendering behind a 90 % opaque panel so the game is never paused.",
                "Opening an app takes < 150 ms; cold data loads (lore, specs) are parsed once at startup and cached.",
                "No network access. Time sources are the game clock, so everything is deterministic for tests (`--seed`)."])
    w("### 2.8 Warp speed model")
    w("")
    w("`speed_ly_per_day(warp) = ship.ly_per_day_at_cruise * (warp / ship.cruise_warp) ^ (10/3)`; ETA days = distance in light-years / speed. "
      "At cruise the ETAs equal the `eta_days` of `lore.json` waypoints. Throttle is clamped to `ship.top_warp`, and to a cap proportional to reactor output below 40 %.")
    w("")
    w("## 3. Mapping screens to applications")
    w("")
    w("### 3.1 Existing screen textures")
    w("")
    w("| Texture (`godot/textures/screens/<name>.png`) | Application |")
    w("|---|---|")
    for t, a in sorted(sd.TEXTURE_MAP.items()):
        w("| `%s` | `%s` |" % (t, a))
    w("")
    w("### 3.2 Resolution order and conventions for new textures")
    w("")
    w("A model screen has a material named `screen_<texture>`. The registry resolves the application in this order, first hit wins:")
    w("")
    w("1. exact name in `texture_map` (`radar`, `warp`, ...);")
    w("2. the longest matching key of `texture_prefix_map`; the name is compared with and without a leading `scr_`, so `scr_reactor_core_2` and `reactor_core_2` both open `reactor`;")
    w("3. the **category** of the host model in `category_map` (for example any `vending` model opens `vending`);")
    w("4. the fallback `computer`.")
    w("")
    w("Convention: new textures are named `scr_<app-key>[_<variant>]`; the `<app-key>` should be one of the prefixes below. Additional prefixes are added to `tools/specs/software_data.py`, never in game code.")
    w("")
    w("| Prefix | Application |")
    w("|---|---|")
    for k, v in sorted(sd.TEXTURE_PREFIX_MAP.items()):
        w("| `%s` | `%s` |" % (k, v))
    w("")
    w("### 3.3 Machine categories without a texture rule")
    w("")
    w("| Category | Application |")
    w("|---|---|")
    for k, v in sorted(sd.CATEGORY_APP.items()):
        w("| `%s` | `%s` |" % (k, v))
    w("")
    w("## 4. The applications")
    w("")
    for n, a in enumerate(sd.APPS, 1):
        app_section(w, n, a)
    w("## 5. QA matrix and glossary")
    w("")
    w("### 5.1 QA matrix")
    w("")
    w("| Check | How | Pass criterion |")
    w("|---|---|---|")
    w("| Every app opens | headless test opens each id from `software.json` | no script error, closes with Esc |")
    w("| Texture routing | for every texture in `texture_map` and `godot/textures/screens` | resolves to a known app id |")
    w("| Data tolerance | delete `specs.json` / `lore.json` in a test copy | apps show DATA LINK DOWN, no crash |")
    w("| World effects | set alert, lock a door, open a breaker, toggle hangar field | the world reacts within one frame |")
    w("| Determinism | run twice with the same seed | identical ShipState dumps |")
    w("| Performance | open each app 60 s | mean frame < 8 ms extra on the reference runner |")
    w("| Accessibility | reduce motion on, keyboard only | all actions reachable, no motion |")
    w("")
    w("### 5.2 Glossary")
    w("")
    w("| Term | Meaning |")
    w("|---|---|")
    for t, m in [("Application (app)", "software that runs inside a terminal overlay, identified by an id"), ("Screen", "an emissive display on a machine model (material `screen_<texture>`)"),
                 ("Terminal overlay", "the full-screen UI opened with E"), ("ShipState", "autoload singleton with the shared ship values"),
                 ("Stardate", "ship calendar value from lore.json, `YYNNN.d`"), ("ly", "light-year"), ("Warp factor", "dimensionless FTL speed setting, see 2.8"),
                 ("Lane", "a jump route between two systems, see lore.json routes"), ("Alert level", "green / yellow / red ship condition")]:
        w("| %s | %s |" % (t, m))
    w("")
    return "\n".join(out) + "\n"


def write_all(root):
    md = generate()
    p = os.path.join(root, "docs", "SOFTWARE_SPEC.md")
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w") as f:
        f.write(md)
    jp = os.path.join(root, "godot", "data", "software.json")
    with open(jp, "w") as f:
        json.dump(software_json(), f, indent=1, sort_keys=False)
        f.write("\n")
    return p, jp


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=ROOT)
    a = ap.parse_args()
    p, jp = write_all(a.root)
    print("wrote", os.path.relpath(p, a.root), os.path.relpath(jp, a.root))


if __name__ == "__main__":
    main()
