"""Placement policy: which component families belong in which room, and what each family is FOR.

This is the design authority for the layout.  `audit.py` fails a room that contains a family that is not allowed
here, and `bom.py` uses CATEGORY_INFO to explain every model in the bill of materials.
"""

# ------------------------------------------------------------------ families allowed everywhere (architecture / services)
UNIVERSAL = {
    "ceilinglight", "ceilingpanel", "panellight", "sconce", "striplight", "wallpanel", "sign", "safety", "beacon", "clock",
    "duct", "pipe", "cabletray", "doorframe", "door", "floorpanel", "pillar", "junction", "valve", "controlpanel", "hatch",
    "noticeboard", "cleaningbot", "bin", "spotlight", "warnlight", "camera", "railing", "fountain", "instrument",
}

# ------------------------------------------------------------------ room specific families (on top of UNIVERSAL)
ROOM = {
    "corF": set(), "corA": set(),
    "lobby": {"bench", "vending", "plant", "display", "fountain", "noticeboard"},
    "towerA": set(), "towerB": set(),
    # ---- deck 1
    "bridge": {"console", "seat", "holo", "display", "terminal", "plant", "locker", "lamp", "railing", "commsunit"},
    "ready": {"desk", "chair", "couch", "table", "tableware", "lamp", "plant", "locker", "display", "terminal", "shelving",
              "galley", "holo", "cabinet", "bench", "telescope"},
    "lounge": {"couch", "chair", "table", "bench", "plant", "lamp", "tableware", "galley", "display", "holo", "telescope",
               "gym", "terminal", "shelving", "cabinet", "vending"},
    "conf": {"table", "chair", "display", "holo", "terminal", "tableware", "plant", "desk", "lamp", "commsunit", "galley", "cabinet"},
    "astro": {"console", "seat", "holo", "display", "telescope", "terminal", "desk", "chair", "antenna", "rack", "sciinstrument",
              "commsunit", "plant", "lamp", "router", "analyzer", "storage"},
    "cabinA": {"bed", "locker", "desk", "chair", "couch", "lamp", "plant", "table", "tableware", "display", "bench", "cabinet",
               "terminal", "shelving"},
    "cabinB": {"bed", "locker", "desk", "chair", "couch", "lamp", "plant", "table", "tableware", "display", "bench", "cabinet",
               "terminal", "shelving"},
    "capt": {"bed", "locker", "desk", "chair", "couch", "table", "tableware", "lamp", "plant", "display", "holo", "galley",
             "shelving", "terminal", "cabinet", "bench", "seat", "telescope"},
    "comms": {"console", "seat", "commsunit", "router", "rack", "antenna", "display", "terminal", "desk", "chair", "holo",
              "plant", "lamp", "storage", "capacitor", "telescope"},
    # ---- deck 2
    "armory": {"weaponrack", "locker", "suitrack", "cabinet", "bench", "table", "shelving", "storagebin", "terminal", "desk",
               "chair", "display", "crate", "forcefield", "cell", "barrel"},
    "galley": {"galley", "table", "chair", "storagebin", "shelving", "cabinet", "tank", "watertank", "tableware", "locker", "barrel",
               "terminal", "display", "crate", "cylinder", "scrubber", "duct"},
    "mess": {"table", "bench", "chair", "tableware", "galley", "vending", "plant", "display", "lamp", "couch", "terminal",
             "holo"},
    "brig": {"cell", "desk", "chair", "bench", "bed", "locker", "storagebin", "terminal", "display", "weaponrack", "forcefield",
             "table", "cabinet", "suitrack"},
    "secoff": {"desk", "chair", "terminal", "display", "locker", "weaponrack", "table", "couch", "cabinet", "holo", "console",
               "seat", "plant", "lamp", "tableware", "galley", "shelving", "forcefield", "bench", "storagebin", "commsunit"},
    "medbay": {"medbed", "medscanner", "medcabinet", "medsupply", "medtool", "surgical", "cryo", "locker", "desk", "chair",
               "terminal", "display", "plant", "bench", "cabinet", "cylinder", "labbench", "analyzer", "couch", "lamp", "shelving",
               "specimen", "microscope", "tableware", "seat", "storagebin", "tank"},
    "rec": {"gym", "bench", "couch", "table", "chair", "locker", "plant", "display", "vending", "tableware", "lamp", "shelving",
            "galley", "holo", "terminal", "cabinet", "desk"},
    "dorm": {"bed", "locker", "desk", "chair", "lamp", "plant", "table", "bench", "couch", "cabinet", "shelving", "display",
             "tableware", "terminal"},
    "sci": {"labbench", "microscope", "analyzer", "sciinstrument", "specimen", "particle", "terminal", "desk", "chair", "display",
            "cabinet", "locker", "cylinder", "storagebin", "shelving", "tank", "telescope", "plant", "holo", "tableware", "medtool",
            "rack", "cryo", "engtool", "lamp", "seat", "barrel"},
    "hydro": {"planter", "plant", "watertank", "tank", "scrubber", "bench", "table", "chair", "tableware", "lamp", "storagebin",
              "terminal", "display", "engtool", "barrel", "cylinder", "microscope", "specimen", "labbench", "cabinet", "shelving",
              "couch", "couch", "galley"},
    # ---- deck 3
    "life": {"scrubber", "watertank", "tank", "cylinder", "console", "display", "terminal", "engtool", "cabinet", "storagebin",
             "barrel", "rack", "desk", "chair", "seat", "generator", "capacitor", "shelving", "locker", "turbine", "coil", "toolbox"},
    "core": {"rack", "storage", "router", "commsunit", "console", "terminal", "display", "desk", "chair", "seat", "capacitor",
             "tank", "engtool", "cabinet", "toolbox", "generator", "holo", "shelving", "locker", "storagebin"},
    "airlock": {"suitrack", "locker", "bench", "forcefield", "console", "cylinder", "engtool", "storagebin", "display", "terminal",
                "tank", "cabinet", "shelving", "desk", "chair", "seat", "toolbox", "crate", "barrel", "medtool"},
    "eng": {"reactor", "coil", "capacitor", "generator", "tank", "turbine", "nozzle", "console", "display", "engtool", "terminal",
            "desk", "chair", "seat", "locker", "toolbox", "storagebin", "cylinder", "particle", "cabinet", "barrel", "shelving",
            "holo", "rack", "watertank", "scrubber", "hangartool", "crate"},
    "shop": {"engtool", "storagebin", "shelving", "locker", "cabinet", "table", "terminal", "desk", "chair", "cylinder", "barrel",
             "toolbox", "hangartool", "loader", "display", "tank", "generator", "crate", "capacitor", "seat", "rack", "bench",
             "pallet", "nozzle", "turbine", "coil", "console"},
    "cargo": {"crate", "pallet", "barrel", "loader", "shelving", "storagebin", "cylinder", "hangartool", "terminal", "display",
              "console", "desk", "chair", "seat", "forcefield", "cabinet", "locker", "toolbox", "tank", "engtool", "suitrack"},
    "aux": {"generator", "capacitor", "coil", "tank", "console", "display", "terminal", "engtool", "cabinet", "desk", "chair",
            "seat", "rack", "turbine", "toolbox", "storagebin", "locker", "cylinder", "barrel", "shelving", "reactor"},
    "depot": {"shelving", "crate", "storagebin", "pallet", "barrel", "cabinet", "locker", "cylinder", "loader", "terminal",
              "desk", "chair", "seat", "display", "console", "capacitor", "nozzle", "turbine", "coil", "engtool", "toolbox",
              "hangartool", "tank", "generator", "rack", "storage", "suitrack", "medcabinet", "medsupply", "weaponrack"},
    "hangar": {"craft", "hangartool", "loader", "crate", "pallet", "barrel", "cylinder", "shelving", "storagebin", "forcefield",
               "engtool", "terminal", "console", "display", "nozzle", "tank", "suitrack", "locker", "toolbox", "cabinet",
               "generator", "turbine", "capacitor", "desk", "chair", "seat", "antenna", "medsupply", "coil"},
}


# ------------------------------------------------------------------ food and drink (blender/starship/components/food*.py)
# Prepared food and drink are table / shelf items; raw produce, harvest crates and hanging produce belong where food is
# grown, stored or prepared; alcohol only where people may take a drink off duty (wardroom, lounge, captain, galley stores).
FOOD_PREPARED = {"meal", "bakery", "dessert", "tray", "drink"}
FOOD_CASUAL = {"can", "bottle"}
FOOD_PRODUCE = {"fruit", "veg", "deli"}
FOOD_STORES = {"ration", "harvest", "hanging"}
FOOD_BAR = {"cocktail", "buffet"}
_FOOD_ROOMS = {
    "galley": FOOD_PREPARED | FOOD_CASUAL | FOOD_PRODUCE | FOOD_STORES | {"buffet"},
    "mess": FOOD_PREPARED | FOOD_CASUAL | FOOD_PRODUCE | {"ration", "buffet"},
    "wardroom": FOOD_PREPARED | FOOD_CASUAL | FOOD_PRODUCE | FOOD_BAR | {"ration"},
    "provisions": FOOD_PRODUCE | FOOD_STORES | FOOD_CASUAL | {"drink"},
    "hydro": {"harvest", "hanging", "fruit", "veg", "drink", "meal", "tray", "bakery", "can"},
    "lounge": FOOD_CASUAL | {"drink", "dessert", "bakery", "fruit", "deli", "tray", "cocktail", "meal"},
    "capt": FOOD_PREPARED | FOOD_CASUAL | {"fruit", "deli", "cocktail"},
    "conf": {"drink", "can", "bottle", "bakery", "fruit", "tray", "dessert"},
    "ready": {"drink", "can", "bottle", "bakery", "fruit", "tray"},
    "bridge": {"drink", "can"},
    "medbay": {"drink", "fruit", "ration", "tray", "meal", "bottle"},
    "rec": FOOD_CASUAL | {"drink", "bakery", "fruit", "dessert", "tray", "meal", "deli"},
    "dorm": {"drink", "can", "bottle", "fruit", "ration", "bakery"},
    "cabinA": {"drink", "can", "bottle", "fruit", "ration", "bakery", "dessert"},
    "cabinB": {"drink", "can", "bottle", "fruit", "ration", "bakery", "dessert"},
    "brig": {"tray", "drink", "ration", "fruit", "bakery"},
    "secoff": {"drink", "can", "bakery", "tray", "meal", "bottle"},
    "armory": {"drink", "can"},
    "lobby": {"can", "bottle"},
    "sci": {"drink", "can", "ration", "fruit"},
    "astro": {"drink", "can", "ration"},
    "comms": {"drink", "can"},
    "eng": {"drink", "can", "ration"},
    "shop": {"drink", "can", "ration"},
    "aux": {"drink", "can"},
    "life": {"drink", "can", "ration"},
    "core": {"drink", "can"},
    "airlock": {"ration", "bottle"},
    "cargo": {"drink", "can", "ration"},
    "depot": {"ration", "veg", "fruit", "deli", "hanging", "harvest", "bottle", "can"},
    "hangar": {"drink", "can", "ration"},
}
# the two rooms the integrator adds: Wardroom & Bar (crew dept) and Provisions Hold / Cold Store (cargo dept)
ROOM["wardroom"] = {"table", "bench", "chair", "couch", "display", "holo", "plant", "lamp", "tableware", "galley", "shelving", "cabinet",
                    "terminal", "vending", "fountain", "telescope", "gym", "seat", "noticeboard"}
ROOM["provisions"] = {"shelving", "storagebin", "crate", "pallet", "barrel", "cylinder", "cabinet", "locker", "tank", "watertank", "galley", "terminal",
                      "display", "loader", "rack", "toolbox", "desk", "chair", "forcefield", "medcabinet", "scrubber", "engtool"}
for _room, _cats in _FOOD_ROOMS.items():
    ROOM.setdefault(_room, set()).update(_cats)


def room_key(room_id):
    """Strip the deck digit of circulation rooms (corF2 -> corF, lobby3 -> lobby, towerA1 -> towerA)."""
    return room_id.rstrip("0123456789") if room_id[-1].isdigit() else room_id


def allowed(room_id):
    return UNIVERSAL | ROOM.get(room_key(room_id), set())


# ------------------------------------------------------------------ what every family is for (BOM explanations)
CATEGORY_INFO = {
    "analyzer": ("Laboratory analyser", "Measures and characterises samples (composition, structure, biology) for the science staff."),
    "antenna": ("Antenna / relay", "Sends and receives subspace and radio traffic; mounted where signal paths and cabling are short."),
    "barrel": ("Drum / cylinder store", "Bulk storage of fluids, chemicals and gases, secured upright so leaks stay contained."),
    "beacon": ("Alert beacon / emergency lamp", "Gives light and visual or audible warning during alarms and power loss."),
    "bakery": ("Bread and baked goods", "Fresh bread, pastries and cakes from the galley oven: morale food that fits any table."),
    "buffet": ("Buffet / display furniture", "Hot-pan serving lines, bakery racks and display cases that let a crowd serve itself."),
    "can": ("Canned drink", "Brand-less soft drinks and cold brew in 150-500 ml aluminium cans; stocked from the vending machines."),
    "bottle": ("Bottle / flask", "Water, wine, spirits, oils and flasks in glass, PET and steel containers."),
    "cocktail": ("Glassware and cocktails", "Bar glasses and mixed drinks for the wardroom, lounge and the captain's table."),
    "dessert": ("Dessert", "Cakes, ice cream and puddings served after the main meal."),
    "deli": ("Cheese, charcuterie and dairy", "Cheeses, cured meats, eggs and spreads: the cold-store items that fill boards and sandwiches."),
    "drink": ("Hot and cold drink", "Coffee, tea, juices, shakes and smoothies at the table."),
    "fruit": ("Fresh fruit", "Fruit from the hydroponics deck and the cold store."),
    "hanging": ("Hanging produce", "Garlic, chilli, herbs and sausages hung to dry and cure on the galley and store walls."),
    "harvest": ("Hydroponic harvest crate", "Crates of freshly picked crops on their way from the grow beds to the galley."),
    "meal": ("Plated meal", "Complete dishes the galley cooks: burgers, pizza, noodles, steak, sushi, salads, curries."),
    "ration": ("Space ration", "Foil pouches, tubes, bars and trays: shelf-stable emergency and mission food."),
    "tray": ("Serving tray / dish", "Meal trays, breakfast and drinks trays, hot pans, tureens and bread baskets used to carry and serve food."),
    "veg": ("Vegetables", "Fresh vegetables from the grow beds, ready to prepare."),
    "bed": ("Bunk / bed", "Sleeping place for crew off shift."),
    "bench": ("Bench seating", "Fixed seating along walls so the floor stays free for circulation."),
    "bin": ("Waste / recycling bin", "Collects waste for the recycler; a clean ship stays habitable."),
    "cabinet": ("Storage cabinet", "Closed storage for supplies the room's staff need daily."),
    "cabletray": ("Cable tray", "Carries power and data cables overhead or along walls, protected and accessible."),
    "camera": ("Security sensor", "Surveillance and access control for the security department."),
    "capacitor": ("Energy storage", "Buffers electrical power so systems ride through peaks and brown-outs."),
    "ceilinglight": ("Ceiling light fixture", "General lighting sized to the task in the room."),
    "ceilingpanel": ("Ceiling service panel", "Covers services above the ceiling while allowing maintenance access."),
    "cell": ("Holding-cell fitting", "Secure detention furniture and control equipment for the brig."),
    "chair": ("Chair", "Seating for desks and tables."),
    "cleaningbot": ("Cleaning drone", "Keeps floors and glass clean without crew time."),
    "clock": ("Ship's clock", "Shared time reference for watch changes."),
    "coil": ("Power coil / conduit", "Generates or channels plasma and field energy for propulsion."),
    "commsunit": ("Communications unit", "Radio and intercom equipment for ship and external communications."),
    "console": ("Workstation console", "Operator station with displays and controls for one ship function."),
    "controlpanel": ("Wall control panel", "Local controls for doors, lights, environment and power."),
    "couch": ("Sofa / lounge seating", "Soft seating for rest and informal meetings."),
    "craft": ("Small craft", "Shuttles and pods for transport, rescue and repair outside the hull."),
    "crate": ("Cargo crate / container", "Palletised or boxed cargo and supplies, stacked to fit the deck loading."),
    "cryo": ("Cryo / stasis equipment", "Preserves patients and samples at cryogenic temperature."),
    "cylinder": ("Gas cylinder / dewar", "Stores compressed or liquefied gases (breathing oxygen, nitrogen) for life support and work."),
    "desk": ("Desk", "Work surface for paperwork and terminals."),
    "display": ("Wall display", "Shows status, plans and sensor data to people in the room."),
    "door": ("Sliding door", "Pressure-tight door between compartments."),
    "doorframe": ("Doorway frame", "Open doorway between spaces that need no door."),
    "duct": ("Ventilation duct / grille", "Moves conditioned air to and from the room."),
    "engtool": ("Engineering tool / equipment", "Tools, carts and test gear for maintenance crews."),
    "floorpanel": ("Floor panel", "Floor finish panel, markings or hatch plate."),
    "forcefield": ("Force-field barrier", "Energy barrier that seals an opening while letting craft or people pass when lowered."),
    "fountain": ("Drinking fountain", "Drinking water for crew."),
    "galley": ("Galley equipment", "Food storage, cooking and dish-washing equipment."),
    "generator": ("Power generator / transformer", "Produces and conditions electrical power for the ship."),
    "gym": ("Exercise equipment", "Keeps the crew fit during long voyages."),
    "hangartool": ("Flight-deck equipment", "Servicing, fuelling, launch and safety gear for craft."),
    "hatch": ("Pressure hatch", "Sealable access to ducts, tanks and compartments."),
    "holo": ("Holographic projector", "Three-dimensional display for briefings and tactical planning."),
    "instrument": ("Measuring instrument", "Gauges and navigation instruments."),
    "junction": ("Electrical junction / cabinet", "Distributes and protects power and data circuits."),
    "labbench": ("Laboratory furniture", "Benches, hoods and stools for safe wet and dry lab work."),
    "lamp": ("Lamp", "Local task or mood lighting."),
    "loader": ("Cargo handling equipment", "Moves pallets and containers without crew strain."),
    "locker": ("Personal / equipment locker", "Secure storage for personal gear and issue equipment."),
    "medbed": ("Patient bed / table", "Examination, treatment and recovery of patients."),
    "medcabinet": ("Medical store", "Drugs, sterile instruments and consumables, locked and labelled."),
    "medscanner": ("Diagnostic scanner", "Imaging and analysis for diagnosis."),
    "medsupply": ("Medical supply / IV", "Consumables and patient-care accessories."),
    "medtool": ("Medical instrument", "Hand instruments and kits at the bedside."),
    "microscope": ("Microscope", "Magnifies samples for analysis."),
    "noticeboard": ("Notice board", "Duty rosters and notices."),
    "nozzle": ("Thruster / nozzle", "Propulsion hardware (installed or held as spare)."),
    "pallet": ("Pallet", "Unit load for forklift handling."),
    "panellight": ("Wall light panel", "Soft indirect light on walls."),
    "particle": ("Particle / plasma apparatus", "Research and power experiments with charged particles."),
    "pillar": ("Structural pillar / beam", "Carries deck loads and frames spaces."),
    "pipe": ("Pipe run", "Carries water, coolant or gas."),
    "planter": ("Hydroponic planter", "Grows food and oxygen-producing plants."),
    "plant": ("Decorative plant", "Improves wellbeing and air quality."),
    "rack": ("Equipment rack", "Houses servers, storage and network gear with cooling."),
    "railing": ("Guard rail", "Stops falls near drops and hazards."),
    "reactor": ("Reactor / power core", "Main and auxiliary power generation."),
    "router": ("Network hardware", "Routes data between ship systems."),
    "safety": ("Safety equipment", "Fire, first-aid, breach and emergency gear required by regulation."),
    "sciinstrument": ("Field / science instrument", "Sensors and field labs for science work."),
    "sconce": ("Wall sconce", "Decorative wall lighting."),
    "scrubber": ("Air scrubber / processor", "Removes CO2 and contaminants from ship air."),
    "seat": ("Crew station seat", "Operator chair for console positions."),
    "shelving": ("Shelving", "Open storage for parts, stores and gear."),
    "sign": ("Sign", "Wayfinding and hazard marking."),
    "specimen": ("Specimen container", "Holds biological and mineral samples safely."),
    "spotlight": ("Spot / flood light", "Bright task lighting for work areas."),
    "storage": ("Data / secure storage", "Archives data and valuables."),
    "storagebin": ("Storage bin / tool chest", "Small-parts and tool storage."),
    "striplight": ("Light strip", "Linear guide lighting."),
    "suitrack": ("Suit / EVA rack", "Stores and dresses pressure suits and breathing kit."),
    "surgical": ("Surgical equipment", "Operating-theatre machines."),
    "table": ("Table", "Work, meeting or dining surface."),
    "tableware": ("Tableware / table setting", "Plates, cups and condiments on tables."),
    "tank": ("Process tank / heat exchanger", "Stores or conditions fluids for ship systems."),
    "telescope": ("Telescope / tracker", "Optical observation and star tracking."),
    "terminal": ("Terminal / datapad", "Data entry and information access."),
    "toolbox": ("Toolbox", "Portable hand tools."),
    "turbine": ("Turbine / pump", "Rotating machinery for power and fluid movement."),
    "valve": ("Valve / gauge", "Controls and monitors fluid lines."),
    "vending": ("Vending machine", "Snacks, drinks and small parts for crew."),
    "warnlight": ("Warning light", "Signals hazards and machine states."),
    "watertank": ("Water treatment", "Stores, purifies and recycles water."),
    "weaponrack": ("Weapon rack / armoury fitting", "Secure storage of weapons and protective gear."),
    "wallpanel": ("Wall panel", "Finished wall cladding."),
}
