"""Placement policy: which component families belong in which room, and what each family is FOR.

This is the design authority for the layout.  `audit.py` fails a room that contains a family that is not allowed
here, and `bom.py` uses CATEGORY_INFO to explain every model in the bill of materials.
"""

# ------------------------------------------------------------------ families allowed everywhere (architecture / services)
UNIVERSAL = {
    "ceilinglight", "ceilingpanel", "panellight", "sconce", "striplight", "wallpanel", "sign", "safety", "beacon", "clock",
    "duct", "pipe", "cabletray", "doorframe", "door", "floorpanel", "pillar", "junction", "valve", "controlpanel", "hatch",
    "noticeboard", "cleaningbot", "bin", "spotlight", "warnlight", "camera", "railing", "fountain", "instrument",
}

# ------------------------------------------------------------------ room specific families (on top of UNIVERSAL)
ROOM = {
    "corF": set(), "corA": set(),
    "lobby": {"bench", "vending", "plant", "display", "fountain", "noticeboard"},
    "towerA": set(), "towerB": set(),
    # ---- deck 1
    "bridge": {"console", "seat", "holo", "display", "terminal", "plant", "locker", "lamp", "railing", "commsunit"},
    "ready": {"desk", "chair", "couch", "table", "tableware", "lamp", "plant", "locker", "display", "terminal", "shelving",
              "galley", "holo", "cabinet", "bench", "telescope"},
    "lounge": {"couch", "chair", "table", "bench", "plant", "lamp", "tableware", "galley", "display", "holo", "telescope",
               "gym", "terminal", "shelving", "cabinet", "vending"},
    "conf": {"table", "chair", "display", "holo", "terminal", "tableware", "plant", "desk", "lamp", "commsunit", "galley", "cabinet"},
    "astro": {"console", "seat", "holo", "display", "telescope", "terminal", "desk", "chair", "antenna", "rack", "sciinstrument",
              "commsunit", "plant", "lamp", "router", "analyzer", "storage"},
    "cabinA": {"bed", "locker", "desk", "chair", "couch", "lamp", "plant", "table", "tableware", "display", "bench", "cabinet",
               "terminal", "shelving"},
    "cabinB": {"bed", "locker", "desk", "chair", "couch", "lamp", "plant", "table", "tableware", "display", "bench", "cabinet",
               "terminal", "shelving"},
    "capt": {"bed", "locker", "desk", "chair", "couch", "table", "tableware", "lamp", "plant", "display", "holo", "galley",
             "shelving", "terminal", "cabinet", "bench", "seat", "telescope"},
    "comms": {"console", "seat", "commsunit", "router", "rack", "antenna", "display", "terminal", "desk", "chair", "holo",
              "plant", "lamp", "storage", "capacitor", "telescope"},
    # ---- deck 2
    "armory": {"weaponrack", "locker", "suitrack", "cabinet", "bench", "table", "shelving", "storagebin", "terminal", "desk",
               "chair", "display", "crate", "forcefield", "cell", "barrel"},
    "galley": {"galley", "table", "chair", "storagebin", "shelving", "cabinet", "tank", "watertank", "tableware", "locker", "barrel",
               "terminal", "display", "crate", "cylinder", "scrubber", "duct"},
    "mess": {"table", "bench", "chair", "tableware", "galley", "vending", "plant", "display", "lamp", "couch", "terminal",
             "holo"},
    "brig": {"cell", "desk", "chair", "bench", "bed", "locker", "storagebin", "terminal", "display", "weaponrack", "forcefield",
             "table", "cabinet", "suitrack"},
    "secoff": {"desk", "chair", "terminal", "display", "locker", "weaponrack", "table", "couch", "cabinet", "holo", "console",
               "seat", "plant", "lamp", "tableware", "galley", "shelving", "forcefield", "bench", "storagebin", "commsunit"},
    "medbay": {"medbed", "medscanner", "medcabinet", "medsupply", "medtool", "surgical", "cryo", "locker", "desk", "chair",
               "terminal", "display", "plant", "bench", "cabinet", "cylinder", "labbench", "analyzer", "couch", "lamp", "shelving",
               "specimen", "microscope", "tableware", "seat", "storagebin", "tank"},
    "rec": {"gym", "bench", "couch", "table", "chair", "locker", "plant", "display", "vending", "tableware", "lamp", "shelving",
            "galley", "holo", "terminal", "cabinet", "desk"},
    "dorm": {"bed", "locker", "desk", "chair", "lamp", "plant", "table", "bench", "couch", "cabinet", "shelving", "display",
             "tableware", "terminal"},
    "sci": {"labbench", "microscope", "analyzer", "sciinstrument", "specimen", "particle", "terminal", "desk", "chair", "display",
            "cabinet", "locker", "cylinder", "storagebin", "shelving", "tank", "telescope", "plant", "holo", "tableware", "medtool",
            "rack", "cryo", "engtool", "lamp", "seat", "barrel"},
    "hydro": {"planter", "plant", "watertank", "tank", "scrubber", "bench", "table", "chair", "tableware", "lamp", "storagebin",
              "terminal", "display", "engtool", "barrel", "cylinder", "microscope", "specimen", "labbench", "cabinet", "shelving",
              "couch", "couch", "galley"},
    # ---- deck 3
    "life": {"scrubber", "watertank", "tank", "cylinder", "console", "display", "terminal", "engtool", "cabinet", "storagebin",
             "barrel", "rack", "desk", "chair", "seat", "generator", "capacitor", "shelving", "locker", "turbine", "coil", "toolbox"},
    "core": {"rack", "storage", "router", "commsunit", "console", "terminal", "display", "desk", "chair", "seat", "capacitor",
             "tank", "engtool", "cabinet", "toolbox", "generator", "holo", "shelving", "locker", "storagebin"},
    "airlock": {"suitrack", "locker", "bench", "forcefield", "console", "cylinder", "engtool", "storagebin", "display", "terminal",
                "tank", "cabinet", "shelving", "desk", "chair", "seat", "toolbox", "crate", "barrel", "medtool"},
    "eng": {"reactor", "coil", "capacitor", "generator", "tank", "turbine", "nozzle", "console", "display", "engtool", "terminal",
            "desk", "chair", "seat", "locker", "toolbox", "storagebin", "cylinder", "particle", "cabinet", "barrel", "shelving",
            "holo", "rack", "watertank", "scrubber", "hangartool", "crate"},
    "shop": {"engtool", "storagebin", "shelving", "locker", "cabinet", "table", "terminal", "desk", "chair", "cylinder", "barrel",
             "toolbox", "hangartool", "loader", "display", "tank", "generator", "crate", "capacitor", "seat", "rack", "bench",
             "pallet", "nozzle", "turbine", "coil", "console"},
    "cargo": {"crate", "pallet", "barrel", "loader", "shelving", "storagebin", "cylinder", "hangartool", "terminal", "display",
              "console", "desk", "chair", "seat", "forcefield", "cabinet", "locker", "toolbox", "tank", "engtool", "suitrack"},
    "aux": {"generator", "capacitor", "coil", "tank", "console", "display", "terminal", "engtool", "cabinet", "desk", "chair",
            "seat", "rack", "turbine", "toolbox", "storagebin", "locker", "cylinder", "barrel", "shelving", "reactor"},
    "depot": {"shelving", "crate", "storagebin", "pallet", "barrel", "cabinet", "locker", "cylinder", "loader", "terminal",
              "desk", "chair", "seat", "display", "console", "capacitor", "nozzle", "turbine", "coil", "engtool", "toolbox",
              "hangartool", "tank", "generator", "rack", "storage", "suitrack", "medcabinet", "medsupply", "weaponrack"},
    "hangar": {"craft", "hangartool", "loader", "crate", "pallet", "barrel", "cylinder", "shelving", "storagebin", "forcefield",
               "engtool", "terminal", "console", "display", "nozzle", "tank", "suitrack", "locker", "toolbox", "cabinet",
               "generator", "turbine", "capacitor", "desk", "chair", "seat", "antenna", "medsupply", "coil"},
    # ---- deck 0 (sky deck)
    "starcart": {"holo", "console", "seat", "display", "telescope", "terminal", "desk", "chair", "antenna", "rack", "sciinstrument",
                 "commsunit", "plant", "lamp", "router", "analyzer", "storage", "bench", "couch", "table", "tableware", "cabinet",
                 "shelving", "railing"},
    "theatre": {"seat", "chair", "display", "holo", "terminal", "console", "desk", "table", "bench", "lamp", "plant", "couch",
                "tableware", "galley", "cabinet", "commsunit", "shelving"},
    "wardroom": {"table", "chair", "couch", "bench", "tableware", "galley", "vending", "plant", "lamp", "display", "holo", "terminal",
                 "cabinet", "shelving", "telescope", "desk", "locker"},
    "library": {"shelving", "table", "chair", "desk", "couch", "lamp", "plant", "terminal", "display", "storage", "cabinet", "bench",
                "holo", "tableware", "seat", "telescope", "locker"},
    "arbor": {"planter", "plant", "watertank", "tank", "bench", "table", "chair", "lamp", "display", "terminal", "tableware", "couch",
              "scrubber", "engtool", "storagebin", "cabinet", "shelving", "specimen", "microscope", "labbench", "galley", "barrel"},
    "observ": {"telescope", "console", "seat", "display", "holo", "terminal", "desk", "chair", "antenna", "sciinstrument", "analyzer",
               "rack", "lamp", "plant", "couch", "bench", "shelving", "cabinet", "storage", "router", "commsunit", "labbench", "table"},
    "flag": {"bed", "locker", "desk", "chair", "couch", "table", "tableware", "lamp", "plant", "display", "holo", "galley", "shelving",
             "terminal", "cabinet", "bench", "seat", "telescope", "vending"},
    # ---- deck 4 (hold deck)
    "antimatter": {"reactor", "coil", "capacitor", "generator", "tank", "turbine", "console", "display", "terminal", "engtool",
                   "toolbox", "storagebin", "cylinder", "particle", "cabinet", "barrel", "rack", "cryo", "nozzle", "seat", "desk",
                   "chair", "locker", "forcefield", "shelving", "suitrack"},
    "provisions": {"crate", "pallet", "barrel", "loader", "shelving", "storagebin", "cylinder", "tank", "cabinet", "locker", "terminal",
                   "display", "console", "desk", "chair", "seat", "cryo", "galley", "tableware", "watertank", "forcefield", "toolbox",
                   "engtool", "planter"},
    "water": {"watertank", "tank", "scrubber", "turbine", "cylinder", "console", "display", "terminal", "engtool", "toolbox",
              "storagebin", "barrel", "cabinet", "locker", "desk", "chair", "seat", "generator", "capacitor", "shelving", "coil",
              "labbench", "analyzer", "rack"},
    "waste": {"watertank", "tank", "scrubber", "turbine", "cylinder", "console", "display", "terminal", "engtool", "toolbox",
              "storagebin", "barrel", "cabinet", "locker", "desk", "chair", "seat", "generator", "capacitor", "shelving", "coil",
              "loader", "crate", "pallet"},
    "fab": {"engtool", "storagebin", "shelving", "locker", "cabinet", "table", "terminal", "desk", "chair", "cylinder", "barrel",
            "toolbox", "hangartool", "loader", "display", "tank", "generator", "crate", "capacitor", "seat", "rack", "bench", "pallet",
            "nozzle", "turbine", "coil", "console", "analyzer", "labbench", "particle", "holo"},
    "auxctl": {"console", "seat", "display", "terminal", "holo", "desk", "chair", "commsunit", "rack", "router", "locker", "cabinet",
               "table", "engtool", "plant", "lamp", "capacitor", "storage", "tank", "suitrack", "tableware", "galley", "antenna"},
    "hold": {"crate", "pallet", "barrel", "loader", "shelving", "storagebin", "cylinder", "hangartool", "terminal", "display", "console",
             "desk", "chair", "seat", "forcefield", "cabinet", "locker", "toolbox", "tank", "engtool", "suitrack", "watertank",
             "generator", "capacitor"},
    "drone": {"craft", "hangartool", "loader", "crate", "pallet", "barrel", "cylinder", "shelving", "storagebin", "engtool", "terminal",
              "console", "display", "nozzle", "tank", "suitrack", "locker", "toolbox", "cabinet", "generator", "turbine", "capacitor",
              "desk", "chair", "seat", "antenna", "coil", "rack", "router", "commsunit", "forcefield"},
}


def room_key(room_id):
    """Strip the deck digit of circulation rooms (corF2 -> corF, lobby3 -> lobby, towerA1 -> towerA)."""
    return room_id.rstrip("0123456789") if room_id[-1].isdigit() else room_id


def allowed(room_id):
    return UNIVERSAL | ROOM.get(room_key(room_id), set())


# ------------------------------------------------------------------ what every family is for (BOM explanations)
CATEGORY_INFO = {
    "analyzer": ("Laboratory analyser", "Measures and characterises samples (composition, structure, biology) for the science staff."),
    "antenna": ("Antenna / relay", "Sends and receives subspace and radio traffic; mounted where signal paths and cabling are short."),
    "barrel": ("Drum / cylinder store", "Bulk storage of fluids, chemicals and gases, secured upright so leaks stay contained."),
    "beacon": ("Alert beacon / emergency lamp", "Gives light and visual or audible warning during alarms and power loss."),
    "bed": ("Bunk / bed", "Sleeping place for crew off shift."),
    "bench": ("Bench seating", "Fixed seating along walls so the floor stays free for circulation."),
    "bin": ("Waste / recycling bin", "Collects waste for the recycler; a clean ship stays habitable."),
    "cabinet": ("Storage cabinet", "Closed storage for supplies the room's staff need daily."),
    "cabletray": ("Cable tray", "Carries power and data cables overhead or along walls, protected and accessible."),
    "camera": ("Security sensor", "Surveillance and access control for the security department."),
    "capacitor": ("Energy storage", "Buffers electrical power so systems ride through peaks and brown-outs."),
    "ceilinglight": ("Ceiling light fixture", "General lighting sized to the task in the room."),
    "ceilingpanel": ("Ceiling service panel", "Covers services above the ceiling while allowing maintenance access."),
    "cell": ("Holding-cell fitting", "Secure detention furniture and control equipment for the brig."),
    "chair": ("Chair", "Seating for desks and tables."),
    "cleaningbot": ("Cleaning drone", "Keeps floors and glass clean without crew time."),
    "clock": ("Ship's clock", "Shared time reference for watch changes."),
    "coil": ("Power coil / conduit", "Generates or channels plasma and field energy for propulsion."),
    "commsunit": ("Communications unit", "Radio and intercom equipment for ship and external communications."),
    "console": ("Workstation console", "Operator station with displays and controls for one ship function."),
    "controlpanel": ("Wall control panel", "Local controls for doors, lights, environment and power."),
    "couch": ("Sofa / lounge seating", "Soft seating for rest and informal meetings."),
    "craft": ("Small craft", "Shuttles and pods for transport, rescue and repair outside the hull."),
    "crate": ("Cargo crate / container", "Palletised or boxed cargo and supplies, stacked to fit the deck loading."),
    "cryo": ("Cryo / stasis equipment", "Preserves patients and samples at cryogenic temperature."),
    "cylinder": ("Gas cylinder / dewar", "Stores compressed or liquefied gases (breathing oxygen, nitrogen) for life support and work."),
    "desk": ("Desk", "Work surface for paperwork and terminals."),
    "display": ("Wall display", "Shows status, plans and sensor data to people in the room."),
    "door": ("Sliding door", "Pressure-tight door between compartments."),
    "doorframe": ("Doorway frame", "Open doorway between spaces that need no door."),
    "duct": ("Ventilation duct / grille", "Moves conditioned air to and from the room."),
    "engtool": ("Engineering tool / equipment", "Tools, carts and test gear for maintenance crews."),
    "floorpanel": ("Floor panel", "Floor finish panel, markings or hatch plate."),
    "forcefield": ("Force-field barrier", "Energy barrier that seals an opening while letting craft or people pass when lowered."),
    "fountain": ("Drinking fountain", "Drinking water for crew."),
    "galley": ("Galley equipment", "Food storage, cooking and dish-washing equipment."),
    "generator": ("Power generator / transformer", "Produces and conditions electrical power for the ship."),
    "gym": ("Exercise equipment", "Keeps the crew fit during long voyages."),
    "hangartool": ("Flight-deck equipment", "Servicing, fuelling, launch and safety gear for craft."),
    "hatch": ("Pressure hatch", "Sealable access to ducts, tanks and compartments."),
    "holo": ("Holographic projector", "Three-dimensional display for briefings and tactical planning."),
    "instrument": ("Measuring instrument", "Gauges and navigation instruments."),
    "junction": ("Electrical junction / cabinet", "Distributes and protects power and data circuits."),
    "labbench": ("Laboratory furniture", "Benches, hoods and stools for safe wet and dry lab work."),
    "lamp": ("Lamp", "Local task or mood lighting."),
    "loader": ("Cargo handling equipment", "Moves pallets and containers without crew strain."),
    "locker": ("Personal / equipment locker", "Secure storage for personal gear and issue equipment."),
    "medbed": ("Patient bed / table", "Examination, treatment and recovery of patients."),
    "medcabinet": ("Medical store", "Drugs, sterile instruments and consumables, locked and labelled."),
    "medscanner": ("Diagnostic scanner", "Imaging and analysis for diagnosis."),
    "medsupply": ("Medical supply / IV", "Consumables and patient-care accessories."),
    "medtool": ("Medical instrument", "Hand instruments and kits at the bedside."),
    "microscope": ("Microscope", "Magnifies samples for analysis."),
    "noticeboard": ("Notice board", "Duty rosters and notices."),
    "nozzle": ("Thruster / nozzle", "Propulsion hardware (installed or held as spare)."),
    "pallet": ("Pallet", "Unit load for forklift handling."),
    "panellight": ("Wall light panel", "Soft indirect light on walls."),
    "particle": ("Particle / plasma apparatus", "Research and power experiments with charged particles."),
    "pillar": ("Structural pillar / beam", "Carries deck loads and frames spaces."),
    "pipe": ("Pipe run", "Carries water, coolant or gas."),
    "planter": ("Hydroponic planter", "Grows food and oxygen-producing plants."),
    "plant": ("Decorative plant", "Improves wellbeing and air quality."),
    "rack": ("Equipment rack", "Houses servers, storage and network gear with cooling."),
    "railing": ("Guard rail", "Stops falls near drops and hazards."),
    "reactor": ("Reactor / power core", "Main and auxiliary power generation."),
    "router": ("Network hardware", "Routes data between ship systems."),
    "safety": ("Safety equipment", "Fire, first-aid, breach and emergency gear required by regulation."),
    "sciinstrument": ("Field / science instrument", "Sensors and field labs for science work."),
    "sconce": ("Wall sconce", "Decorative wall lighting."),
    "scrubber": ("Air scrubber / processor", "Removes CO2 and contaminants from ship air."),
    "seat": ("Crew station seat", "Operator chair for console positions."),
    "shelving": ("Shelving", "Open storage for parts, stores and gear."),
    "sign": ("Sign", "Wayfinding and hazard marking."),
    "specimen": ("Specimen container", "Holds biological and mineral samples safely."),
    "spotlight": ("Spot / flood light", "Bright task lighting for work areas."),
    "storage": ("Data / secure storage", "Archives data and valuables."),
    "storagebin": ("Storage bin / tool chest", "Small-parts and tool storage."),
    "striplight": ("Light strip", "Linear guide lighting."),
    "suitrack": ("Suit / EVA rack", "Stores and dresses pressure suits and breathing kit."),
    "surgical": ("Surgical equipment", "Operating-theatre machines."),
    "table": ("Table", "Work, meeting or dining surface."),
    "tableware": ("Tableware / table setting", "Plates, cups and condiments on tables."),
    "tank": ("Process tank / heat exchanger", "Stores or conditions fluids for ship systems."),
    "telescope": ("Telescope / tracker", "Optical observation and star tracking."),
    "terminal": ("Terminal / datapad", "Data entry and information access."),
    "toolbox": ("Toolbox", "Portable hand tools."),
    "turbine": ("Turbine / pump", "Rotating machinery for power and fluid movement."),
    "valve": ("Valve / gauge", "Controls and monitors fluid lines."),
    "vending": ("Vending machine", "Snacks, drinks and small parts for crew."),
    "warnlight": ("Warning light", "Signals hazards and machine states."),
    "watertank": ("Water treatment", "Stores, purifies and recycles water."),
    "weaponrack": ("Weapon rack / armoury fitting", "Secure storage of weapons and protective gear."),
    "wallpanel": ("Wall panel", "Finished wall cladding."),
}
