#!/usr/bin/env python3
"""Generate the engineering drawing set (SVG sheets + INDEX.md) from godot/data/ship.json.

    python tools/draft/draft.py --ship godot/data/ship.json --catalog godot/data/catalog.json --out docs/drafts [--png]

Pure standard library.  Output is deterministic (no timestamps, stable ordering).  With --png the general
arrangement and contact sheets are also rasterised with headless Chromium (optional, not needed by CI).
"""
import argparse
import os
import shutil
import struct
import subprocess
import sys
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import shipmodel as model  # noqa: E402

CHROME_CANDIDATES = ["/opt/pw-browsers/chromium-1194/chrome-linux/chrome", "chromium", "chromium-browser", "google-chrome", "chrome"]


def slugify(s):
    s = "".join(ch if ch.isalnum() else "_" for ch in s.lower())
    while "__" in s:
        s = s.replace("__", "_")
    return s.strip("_")


def filename(sh):
    return "%s_%s.svg" % (sh.num, sh.slug or slugify(sh.title))


def build_sheets(ship, only=None):
    """Returns the ordered list of Sheet objects: G-01..G-16, K-01..K-03, then three sheets per room."""
    import sheets_room
    import sheets_ga
    import sheets_misc
    rooms = [r for r in ship.rooms if not only or r.id in only]
    room_sheets = []
    for room in rooms:
        room_sheets.append(sheets_room.room_plan(ship, room))
        room_sheets.append(sheets_room.room_section(ship, room, "SL"))
        room_sheets.append(sheets_room.room_section(ship, room, "ST"))
    if only:
        return room_sheets
    g = [sheets_ga.deck_ga(ship, d) for d in (1, 2, 3)]
    g.append(sheets_ga.hull_lines(ship))
    g.append(sheets_ga.profile_sheet(ship))
    g += [sheets_ga.ship_section(ship, e) for e in sheets_ga.SECTION_CUTS]
    g.append(sheets_misc.stair_sheet(ship))
    g.append(sheets_misc.circulation_sheet(ship))
    g.append(sheets_misc.schedule_sheet(ship))
    files = {}
    for sh in room_sheets:
        if sh.num.endswith("-P"):
            files[sh.num[2:-2]] = filename(sh)
    k = [sheets_misc.contact_sheet(ship, d, files) for d in (1, 2, 3)]
    listing = [(sh.num, sh.title, sh.scale) for sh in g] + [("G-16", "Drawing index, legend and symbols", "NTS")] + \
              [(sh.num, sh.title, sh.scale) for sh in k]
    g.append(sheets_misc.index_sheet(ship, listing))
    import sheets_spec   # specification sheets S-01.. (power diagram, budgets, machine datasheets); none if specs.json is missing
    return g + k + sheets_spec.spec_sheets(ship) + room_sheets


def write_index(out, sheets, ship):
    groups = [("General arrangement and contact sheets", lambda s: s.num[0] in "GK"), ("Specification sheets (power, budgets, machine datasheets)", lambda s: s.num[0] == "S")]
    for d in (1, 2, 3):
        groups.append(("Deck %d - %s (room sheets)" % (d, ship.deck_name[d]), (lambda dd: lambda s: s.num[0] == "R" and s.deck == "DECK %d" % dd)(d)))
    lines = ["# Starshipgo engineering drawings", "",
             "Generated by `python tools/draft/draft.py --ship godot/data/ship.json --catalog godot/data/catalog.json --out docs/drafts`.",
             "Every sheet is A3 landscape (420 x 297 mm); dimensions in millimetres, levels in metres; revision A.", "",
             "%d sheets: %d general sheets, %d room sheets (plan `-P`, longitudinal section `-SL`, transverse section `-ST` per room)." % (
                 len(sheets), sum(1 for s in sheets if s.num[0] in "GK"), sum(1 for s in sheets if s.num[0] == "R")), ""]
    for title, pred in groups:
        sel = [s for s in sheets if pred(s)]
        if not sel:
            continue
        lines += ["## " + title, "", "| Sheet | Title | Scale | File |", "|---|---|---|---|"]
        for s in sel:
            f = filename(s)
            lines.append("| %s | %s | %s | [%s](%s) |" % (s.num, s.title.replace("|", "/"), s.scale, f, f))
        lines.append("")
    with open(os.path.join(out, "INDEX.md"), "w") as fh:
        fh.write("\n".join(lines))


# ------------------------------------------------------------------ PNG export (optional)
def find_chrome():
    for c in CHROME_CANDIDATES:
        p = c if os.path.isabs(c) else shutil.which(c)
        if p and os.path.exists(p):
            return p
    return None


def crop_png(path, w, h):
    """Crop a PNG to its top-left w x h (8-bit, non-interlaced) using only zlib/struct."""
    data = open(path, "rb").read()
    pos = 8
    idat = b""
    ihdr = None
    while pos < len(data):
        ln, = struct.unpack(">I", data[pos:pos + 4])
        typ = data[pos + 4:pos + 8]
        body = data[pos + 8:pos + 8 + ln]
        if typ == b"IHDR":
            ihdr = body
        elif typ == b"IDAT":
            idat += body
        pos += 12 + ln
    W, H, depth, ctype, _, _, inter = struct.unpack(">IIBBBBB", ihdr)
    if inter or depth != 8 or h >= H:
        return
    bpp = {0: 1, 2: 3, 4: 2, 6: 4}[ctype]
    raw = zlib.decompress(idat)
    stride = 1 + W * bpp
    rows = raw[:stride * h]
    if w < W:          # narrowing needs unfiltering; only crop the height
        w = W

    def chunk(t, b):
        c = struct.pack(">I", len(b)) + t + b
        return c + struct.pack(">I", zlib.crc32(t + b) & 0xffffffff)
    out = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", W, h, depth, ctype, 0, 0, 0)) + \
        chunk(b"IDAT", zlib.compress(rows, 9)) + chunk(b"IEND", b"")
    open(path, "wb").write(out)


SHOWCASE = {"R-bridge-P", "R-mess-P", "R-mess-SL", "R-eng-P", "R-medbay-ST", "R-hangar-SL"}   # room sheets rasterised for the README


def export_png(out, sheets):
    chrome = find_chrome()
    if not chrome:
        print("no Chromium found - skipping PNG export")
        return 0
    pdir = os.path.join(out, "png")
    os.makedirs(pdir, exist_ok=True)
    n = 0
    W, H = 1587, 1123          # 420 x 297 mm at 96 dpi
    for sh in sheets:
        if sh.num[0] not in "GK" and sh.num not in SHOWCASE:
            continue
        svg = os.path.abspath(os.path.join(out, filename(sh)))
        png = os.path.join(pdir, filename(sh)[:-4] + ".png")
        # headless Chromium reserves ~88 px of browser chrome: ask for a taller window and crop
        cmd = [chrome, "--headless", "--no-sandbox", "--disable-gpu", "--hide-scrollbars", "--screenshot=" + png,
               "--window-size=%d,%d" % (W, H + 88), "file://" + svg]
        subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=120)
        if os.path.exists(png):
            crop_png(png, W, H)
            n += 1
    return n


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ship", default="godot/data/ship.json")
    ap.add_argument("--catalog", default="godot/data/catalog.json")
    ap.add_argument("--out", default="docs/drafts")
    ap.add_argument("--png", action="store_true", help="also rasterise the G and K sheets and a few showcase room sheets (headless Chromium)")
    ap.add_argument("--only", default="", help="comma separated room ids (debug)")
    a = ap.parse_args(argv)
    ship = model.Ship(a.ship, a.catalog)
    os.makedirs(a.out, exist_ok=True)
    sheets = build_sheets(ship, set(a.only.split(",")) if a.only else None)
    for sh in sheets:
        with open(os.path.join(a.out, filename(sh)), "w", newline="\n") as f:
            f.write(sh.render())
    if not a.only:
        write_index(a.out, sheets, ship)
    print("%d sheets -> %s" % (len(sheets), a.out))
    if a.png:
        print("%d PNG files" % export_png(a.out, sheets))


if __name__ == "__main__":
    main()
