#!/usr/bin/env python3
"""Generate the engineering drawing set (SVG sheets + INDEX.md) from godot/data/ship.json.

    python tools/draft/draft.py --ship godot/data/ship.json --catalog godot/data/catalog.json --out docs/drafts [--png]

Pure standard library.  Output is deterministic (no timestamps, stable ordering).  With --png the general
arrangement and contact sheets are also rasterised with headless Chromium (optional, not needed by CI).
"""
import argparse
import os
import shutil
import struct
import subprocess
import sys
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import shipmodel as model  # noqa: E402

CHROME_CANDIDATES = ["/opt/pw-browsers/chromium-1194/chrome-linux/chrome", "chromium", "chromium-browser", "google-chrome", "chrome"]


def slugify(s):
    s = "".join(ch if ch.isalnum() else "_" for ch in s.lower())
    while "__" in s:
        s = s.replace("__", "_")
    return s.strip("_")


def filename(sh):
    return "%s_%s.svg" % (sh.num, sh.slug or slugify(sh.title))


def build_sheets(ship, only=None):
    """Returns the ordered list of Sheet objects: G-01..G-20 (one deck plan per deck, hull, sections, stairs, ...), one contact
    sheet K-xx per deck, then three sheets per room."""
    import sheets_room
    import sheets_ga
    import sheets_hull
    import sheets_misc
    rooms = [r for r in ship.rooms if not only or r.id in only]
    room_sheets = []
    for room in rooms:
        room_sheets.append(sheets_room.room_plan(ship, room))
        room_sheets.append(sheets_room.room_section(ship, room, "SL"))
        room_sheets.append(sheets_room.room_section(ship, room, "ST"))
    if only:
        return room_sheets
    g = {}
    slots = sheets_ga.deck_sheet_numbers(ship, 19)             # decks 1..3 keep G-01..G-03, other decks follow after G-18
    for d in ship.deck_ids:
        sh = sheets_ga.deck_ga(ship, d, "G-%02d" % slots[d])
        g[sh.num] = sh
    for sh in [sheets_hull.hull_lines(ship), sheets_hull.profile_sheet(ship)] + \
            [sheets_ga.ship_section(ship, e) for e in sheets_ga.SECTION_CUTS] + \
            [sheets_misc.stair_sheet(ship), sheets_misc.circulation_sheet(ship), sheets_misc.schedule_sheet(ship),
             sheets_hull.body_plan(ship, "G-17"), sheets_hull.particulars_sheet(ship, "G-18")]:
        if sh is not None:                                    # a ship without stairs has no stair-tower sheet
            g[sh.num] = sh
    files = {}
    for sh in room_sheets:
        if sh.num.endswith("-P"):
            files[sh.num[2:-2]] = filename(sh)
    kslots = sheets_ga.deck_sheet_numbers(ship, 4)
    k = {}
    for d in ship.deck_ids:
        sh = sheets_misc.contact_sheet(ship, d, files, "K-%02d" % kslots[d])
        k[sh.num] = sh
    listing = [(sh.num, sh.title, sh.scale) for sh in g.values()] + [("G-16", "Drawing index, legend and symbols", "NTS")] + \
              [(sh.num, sh.title, sh.scale) for sh in k.values()]
    idx = sheets_misc.index_sheet(ship, sorted(listing))
    g[idx.num] = idx
    import sheets_spec   # specification sheets S-01.. (power diagram, budgets, machine datasheets); none if specs.json is missing
    return [g[n] for n in sorted(g)] + [k[n] for n in sorted(k)] + sheets_spec.spec_sheets(ship) + room_sheets


def write_index(out, sheets, ship):
    groups = [("General arrangement and contact sheets", lambda s: s.num[0] in "GK"), ("Specification sheets (power, budgets, machine datasheets)", lambda s: s.num[0] == "S")]
    for d in ship.deck_ids:
        groups.append(("Deck %d - %s (room sheets)" % (d, ship.deck_name[d]), (lambda dd: lambda s: s.num[0] == "R" and s.deck == "DECK %d" % dd)(d)))
    lines = ["# Starshipgo engineering drawings", "",
             "Generated by `python tools/draft/draft.py --ship godot/data/ship.json --catalog godot/data/catalog.json --out docs/drafts`.",
             "Every sheet is A3 landscape (420 x 297 mm); dimensions in millimetres, levels in metres; revision A.", "",
             "%d sheets: %d general sheets, %d room sheets (plan `-P`, longitudinal section `-SL`, transverse section `-ST` per room)." % (
                 len(sheets), sum(1 for s in sheets if s.num[0] in "GK"), sum(1 for s in sheets if s.num[0] == "R")), "",
             "The ship has %d decks (%s, top to bottom) under a smooth outer skin; the hull sheets G-04, G-05, G-17 and G-18 and every section "
             "G-06 to G-12 draw that skin. Deck plans G-01 to G-03 are decks 1 to 3 (historic numbers); the other decks follow after G-18. "
             "Stations are every 6 m from the forward perpendicular." % (len(ship.deck_ids), ", ".join("%d %s" % (d, ship.deck_name[d]) for d in ship.deck_ids)), ""]
    for title, pred in groups:
        sel = [s for s in sheets if pred(s)]
        if not sel:
            continue
        lines += ["## " + title, "", "| Sheet | Title | Scale | File |", "|---|---|---|---|"]
        for s in sel:
            f = filename(s)
            lines.append("| %s | %s | %s | [%s](%s) |" % (s.num, s.title.replace("|", "/"), s.scale, f, f))
        lines.append("")
    with open(os.path.join(out, "INDEX.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")


# ------------------------------------------------------------------ PNG export (optional)
def find_chrome():
    for c in CHROME_CANDIDATES:
        p = c if os.path.isabs(c) else shutil.which(c)
        if p and os.path.exists(p):
            return p
    return None


def _unfilter(raw, W, H, bpp):
    """Undo the PNG scanline filters; returns the H rows (bytes, no filter byte)."""
    stride = W * bpp
    rows, prev = [], bytearray(stride)
    pos = 0
    for _ in range(H):
        ft = raw[pos]
        cur = bytearray(raw[pos + 1:pos + 1 + stride])
        pos += 1 + stride
        for i in range(stride):
            a = cur[i - bpp] if i >= bpp else 0
            b = prev[i]
            c = prev[i - bpp] if i >= bpp else 0
            if ft == 1:
                cur[i] = (cur[i] + a) & 255
            elif ft == 2:
                cur[i] = (cur[i] + b) & 255
            elif ft == 3:
                cur[i] = (cur[i] + ((a + b) >> 1)) & 255
            elif ft == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                cur[i] = (cur[i] + pr) & 255
        rows.append(bytes(cur))
        prev = cur
    return rows


def crop_png(path, w, h):
    """Crop a PNG to its top-left w x h (8-bit, non-interlaced, colour types 0/2/4/6) using only zlib/struct.
    Returns True when the file was rewritten."""
    with open(path, "rb") as f:
        data = f.read()
    pos = 8
    idat = b""
    ihdr = None
    while pos < len(data):
        ln, = struct.unpack(">I", data[pos:pos + 4])
        typ = data[pos + 4:pos + 8]
        body = data[pos + 8:pos + 8 + ln]
        if typ == b"IHDR":
            ihdr = body
        elif typ == b"IDAT":
            idat += body
        pos += 12 + ln
    W, H, depth, ctype, _, _, inter = struct.unpack(">IIBBBBB", ihdr)
    if inter or depth != 8 or ctype not in (0, 2, 4, 6) or (h >= H and w >= W):
        return False
    bpp = {0: 1, 2: 3, 4: 2, 6: 4}[ctype]
    h, w = min(h, H), min(w, W)
    raw = zlib.decompress(idat)
    rows = b"".join(b"\x00" + r[:w * bpp] for r in _unfilter(raw, W, H, bpp)[:h])

    def chunk(t, b):
        c = struct.pack(">I", len(b)) + t + b
        return c + struct.pack(">I", zlib.crc32(t + b) & 0xffffffff)
    out = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, depth, ctype, 0, 0, 0)) + \
        chunk(b"IDAT", zlib.compress(rows, 9)) + chunk(b"IEND", b"")
    with open(path, "wb") as f:
        f.write(out)
    return True


SHOWCASE = {"R-bridge-P", "R-mess-P", "R-mess-SL", "R-eng-P", "R-medbay-ST", "R-hangar-SL"}   # room sheets rasterised for the README


def export_png(out, sheets):
    chrome = find_chrome()
    if not chrome:
        print("no Chromium found - skipping PNG export")
        return 0
    pdir = os.path.join(out, "png")
    os.makedirs(pdir, exist_ok=True)
    n = 0
    W, H = 1587, 1123          # 420 x 297 mm at 96 dpi
    for sh in sheets:
        if sh.num[0] not in "GK" and sh.num not in SHOWCASE:
            continue
        svg = os.path.abspath(os.path.join(out, filename(sh)))
        png = os.path.join(pdir, filename(sh)[:-4] + ".png")
        # headless Chromium reserves ~88 px of browser chrome: ask for a taller window and crop
        cmd = [chrome, "--headless", "--no-sandbox", "--disable-gpu", "--hide-scrollbars", "--screenshot=" + png,
               "--window-size=%d,%d" % (W, H + 88), "file://" + svg]
        try:
            subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=120)
        except subprocess.TimeoutExpired:
            print("Chromium timed out on %s - skipped" % png)
            continue
        if os.path.exists(png):
            crop_png(png, W, H)
            n += 1
    return n


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ship", default="godot/data/ship.json")
    ap.add_argument("--catalog", default="godot/data/catalog.json")
    ap.add_argument("--out", default="docs/drafts")
    ap.add_argument("--png", action="store_true", help="also rasterise the G and K sheets and a few showcase room sheets (headless Chromium)")
    ap.add_argument("--only", default="", help="comma separated room ids (debug)")
    a = ap.parse_args(argv)
    ship = model.Ship(a.ship, a.catalog)
    os.makedirs(a.out, exist_ok=True)
    only = set(a.only.split(",")) if a.only else None
    if only and not only <= set(ship.by_id):
        ap.error("unknown room id(s): %s; rooms are: %s" % (", ".join(sorted(only - set(ship.by_id))), ", ".join(sorted(ship.by_id))))
    sheets = build_sheets(ship, only)
    for sh in sheets:
        with open(os.path.join(a.out, filename(sh)), "w", newline="\n") as f:
            f.write(sh.render())
    if not a.only:
        write_index(a.out, sheets, ship)
    print("%d sheets -> %s" % (len(sheets), a.out))
    if a.png:
        print("%d PNG files" % export_png(a.out, sheets))


if __name__ == "__main__":
    main()
