"""Specification sheets (S-01...): power single-line diagram, mass / power / price bars and machine datasheet sheets.

Numbers come from godot/data/specs.json (generated by tools/specs/gen_specs.py); if that file is missing nothing is produced.
"""
import os
import sys

from svgkit import Sheet, nice_scale

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools", "specs"))
import specagg  # noqa: E402

DEPT = {"command": "Command", "transit": "Circulation", "crew": "Crew", "security": "Security", "engineering": "Engineering", "cargo": "Cargo / hangar",
        "science": "Science", "life": "Life support", "medical": "Medical"}
HEROES = ["reactor_fusion_core_reactor", "coil_warp_coil_stack", "generator_micro_fusion_generator", "capacitor_battery_rack", "console_helm",
          "medscanner_whole_body_scanner_arch", "medbed_diagnostic_biobed", "scrubber_co2_scrubber_tower", "planter_wheat_tray_bed",
          "rack_computer_core_cabinet", "galley_food_replicator", "forcefield_hangar_field_arch", "craft_shuttlecraft"]
ROLE = {"c": "consumer", "p": "passive", "g": "producer", "s": "energy storage", "x": "converter"}
BAR = "#6f8fbf"


def fw(w):
    if w >= 1e6:
        return "%.2f MW" % (w / 1e6)
    if w >= 1e3:
        return "%.1f kW" % (w / 1e3)
    return "%.0f W" % w


def fkg(kg):
    return "%.2f t" % (kg / 1000.0) if kg >= 1000 else "%.1f kg" % kg


def fcr(c):
    return "%.2f M cr" % (c / 1e6) if c >= 1e6 else ("{:,.0f} cr".format(c))


def wrap(s, n):
    out, line = [], ""
    for word in str(s).split():
        if len(line) + len(word) + 1 > n and line:
            out.append(line)
            line = word
        else:
            line = (line + " " + word).strip()
    if line:
        out.append(line)
    return out


def load_specs():
    return specagg.load_specs(ROOT)


def totals(ship):
    specs = load_specs()
    raw = ship.raw
    rt = {r["id"]: specagg.room_totals(r, raw, specs) for r in raw["rooms"]}
    deck, dept, tot = {}, {}, specagg.blank()
    for r in raw["rooms"]:
        specagg.merge(deck.setdefault(r["deck"], specagg.blank()), rt[r["id"]])
        specagg.merge(dept.setdefault(r["dept"], specagg.blank()), rt[r["id"]])
        specagg.merge(tot, rt[r["id"]])
    return specs, rt, deck, dept, tot


def box(sh, x, y, w, h, lines, fill="#eef1f6", size=1.8, bold_first=True):
    sh.rect(x, y, w, h, "m", fill)
    n = len(lines)
    for i, t in enumerate(lines):
        sh.text(x + w / 2, y + h / 2 + (i - (n - 1) / 2.0) * (size + 0.9) + size * 0.35, t, size, "middle", bold=(bold_first and i == 0), maxw=w - 1.5)


# ------------------------------------------------------------------ S-01 single-line diagram
def power_sld(ship, specs, rt, deck, dept, tot):
    sh = Sheet("S-01", "Power distribution single-line diagram", "SOURCES, MAIN BUS, DECK FEEDERS AND DEPARTMENT LOADS (TYPICAL LOAD PER DATASHEETS)", "NTS", "ALL", "ALL",
               "Electrical", slug="power_single_line_diagram")
    raw = ship.raw
    gens = {}
    stores = {}
    for r in raw["rooms"]:
        for m in specagg.room_items(r, raw):
            s = specs.get(m)
            if s and s["r"] == "g":
                gens.setdefault(m, [0, r["id"]])[0] += 1
            elif s and s["r"] == "s":
                stores.setdefault(m, [0, r["id"]])[0] += 1
    sh.text(16, 14, "GENERATION: %.1f MW   |   TYPICAL LOAD %s   |   CONNECTED PEAK %s   |   BATTERIES %.0f kWh" % (
        tot["gen_kw"] / 1000, fw(tot["typ"]), fw(tot["peak"]), tot["cap_kwh"]), 2.6, bold=True)
    # sources
    x0, bus_x = 16, 112
    src = sorted(gens.items(), key=lambda kv: -specs[kv[0]]["gen"] * kv[1][0])
    y = 24
    sh.text(x0, y - 2, "SOURCES", 2.2, bold=True)
    rows = len(src) + (1 if stores else 0)
    step = min(16.0, (236 - y) / max(1, rows))
    ys = []
    for m, (n, room) in src:
        s = specs[m]
        box(sh, x0, y, 70, step - 3, ["%s x%d" % (s["d"].split(" - ")[-1], n), "%s  %s" % (fw(s["gen"] * 1000 * n), s["v"]), "room %s" % room], "#e4efe0")
        sh.line(x0 + 70, y + (step - 3) / 2, bus_x, y + (step - 3) / 2, "m")
        ys.append(y + (step - 3) / 2)
        y += step
    if stores:
        cap = sum(specs[m]["cap"] * n for m, (n, _r) in stores.items())
        box(sh, x0, y, 70, step - 3, ["Battery / capacitor banks", "%.0f kWh  %.1f MW" % (cap, sum(specs[m]["gen"] * n for m, (n, _r) in stores.items()) / 1000), "%d units" % sum(n for n, _r in stores.values())], "#f1ead7")
        sh.line(x0 + 70, y + (step - 3) / 2, bus_x, y + (step - 3) / 2, "m")
        ys.append(y + (step - 3) / 2)
    # decks
    decks = sorted(raw["decks"], key=lambda d: d["id"])
    avail_h = 236 - 20
    blk = avail_h / max(1, len(decks))
    sh.rect(bus_x - 1.5, 20, 3, 216, "h", "#333")
    sh.text(bus_x, 19, "MAIN BUS", 1.8, "middle", bold=True)
    bx = 138
    for i, d in enumerate(decks):
        by = 22 + i * blk
        t = deck[d["id"]]
        box(sh, bx, by + blk / 2 - 7, 46, 14, ["Deck %d feeder" % d["id"], d["name"], "%s typ / %s pk" % (fw(t["typ"]), fw(t["peak"]))], "#dfe6f2", 1.7)
        sh.line(bus_x, by + blk / 2, bx, by + blk / 2, "m")
        depts = sorted({r["dept"] for r in raw["rooms"] if r["deck"] == d["id"]})
        cols = 3
        cw, chh = 56, 9.5
        sx = bx + 54
        rows_n = (len(depts) + cols - 1) // cols
        sy0 = by + blk / 2 - rows_n * (chh + 2) / 2
        sh.line(bx + 46, by + blk / 2, sx - 3, by + blk / 2, "m")
        sh.line(sx - 3, sy0 + chh / 2, sx - 3, sy0 + (rows_n - 1) * (chh + 2) + chh / 2, "m")
        for k, dp in enumerate(depts):
            tt = specagg.blank()
            for r in raw["rooms"]:
                if r["deck"] == d["id"] and r["dept"] == dp:
                    specagg.merge(tt, rt[r["id"]])
            cx = sx + (k % cols) * (cw + 1.5)
            cy = sy0 + (k // cols) * (chh + 2)
            if k % cols == 0:
                sh.line(sx - 3, cy + chh / 2, sx, cy + chh / 2, "m")
            box(sh, cx, cy, cw, chh, [DEPT.get(dp, dp), fw(tt["typ"])], "#ffffff", 1.7)
    sh.text(236, 244, "Loads: sum of the typical figures of the placed machines (docs/MACHINE_SPECS.md); producers and batteries as rated.", 1.5, fill="#444")
    return sh


# ------------------------------------------------------------------ S-02 bars
def bar_group(sh, x, y, title, rows, unit, fmt, maxw=88.0):
    sh.text(x, y - 3, title, 2.3, bold=True)
    mx = max([v for _n, v in rows] or [1]) or 1
    for i, (n, v) in enumerate(rows):
        yy = y + i * 6.2
        sh.text(x, yy + 3.2, n, 1.8, maxw=34)
        w = maxw * v / mx
        sh.rect(x + 36, yy, max(w, 0.2), 4.2, "n", BAR)
        sh.text(x + 36 + w + 1.2, yy + 3.2, fmt(v), 1.7)
    return y + len(rows) * 6.2


def bar_sheet(ship, specs, rt, deck, dept, tot):
    sh = Sheet("S-02", "Mass, power and price by deck and department", "INSTALLED EQUIPMENT PER THE MACHINE DATASHEETS", "NTS", "ALL", "ALL", "Budgets",
               slug="mass_power_price_by_deck")
    decks = sorted(ship.raw["decks"], key=lambda d: d["id"])
    drows = lambda f: [("Deck %d %s" % (d["id"], d["name"]), f(deck[d["id"]])) for d in decks]
    prows = lambda f: [(DEPT.get(k, k), f(v)) for k, v in sorted(dept.items(), key=lambda kv: -f(kv[1]))]
    bar_group(sh, 16, 22, "MASS BY DECK (t)", drows(lambda t: t["kg"] / 1000.0), "t", lambda v: "%.1f t" % v)
    bar_group(sh, 16, 22 + 8 + 6.2 * len(decks), "TYPICAL POWER BY DECK", drows(lambda t: t["typ"]), "W", fw)
    bar_group(sh, 16, 22 + 16 + 12.4 * len(decks), "EQUIPMENT VALUE BY DECK", drows(lambda t: t["cr"]), "cr", fcr)
    bar_group(sh, 224, 22, "MASS BY DEPARTMENT (t)", prows(lambda t: t["kg"] / 1000.0), "t", lambda v: "%.1f t" % v)
    nd = len(dept)
    bar_group(sh, 224, 22 + 8 + 6.2 * nd, "TYPICAL POWER BY DEPARTMENT", prows(lambda t: t["typ"]), "W", fw)
    bar_group(sh, 224, 22 + 16 + 12.4 * nd, "EQUIPMENT VALUE BY DEPARTMENT", prows(lambda t: t["cr"]), "cr", fcr)
    sh.text(16, 244, "Totals: %s, %s typical / %s peak, %s, %d items." % (fkg(tot["kg"]), fw(tot["typ"]), fw(tot["peak"]), fcr(tot["cr"]), tot["n"]), 2.0, bold=True)
    return sh


# ------------------------------------------------------------------ datasheets
def views(sh, w, h, d, x0, y0, aw, ah):
    """Three orthographic bounding-box views (front, side, top) in the box x0,y0,aw,ah; returns the scale denominator."""
    n = nice_scale(aw - 60, ah - 40, w + d, h + d, options=(2, 5, 10, 20, 25, 50, 75, 100, 150, 200, 250, 300, 400, 500, 750, 1000))
    k = 1000.0 / n
    fx, fy = x0 + 18, y0 + 18            # front view top-left
    sh.rect(fx, fy, w * k, h * k, "m", "#eef1f6")
    sh.rect(fx + w * k * 0.04, fy + h * k * 0.04, w * k * 0.92, h * k * 0.92, "x")
    sh.text(fx, fy - 2.5, "FRONT", 1.8, bold=True)
    sx = fx + w * k + 22                  # side view
    sh.rect(sx, fy, d * k, h * k, "m", "#eef1f6")
    sh.text(sx, fy - 2.5, "SIDE", 1.8, bold=True)
    ty = fy + h * k + 22                  # top view
    sh.rect(fx, ty, w * k, d * k, "m", "#eef1f6")
    sh.text(fx, ty - 2.5, "TOP", 1.8, bold=True)
    sh.dim_h(fx, fx + w * k, fy + h * k + 7, "%d" % round(w * 1000), ext_y=fy + h * k)
    sh.dim_v(fy, fy + h * k, fx - 7, "%d" % round(h * 1000), ext_x=fx)
    sh.dim_h(sx, sx + d * k, fy + h * k + 7, "%d" % round(d * 1000), ext_y=fy + h * k)
    sh.dim_v(ty, ty + d * k, fx - 7, "%d" % round(d * 1000), ext_x=fx)
    return n


def datasheet(ship, specs, mid, num):
    s = specs[mid]
    w, h, d = [v / 1000.0 for v in s["dim"]]
    sh = Sheet(num, "Datasheet - " + s["d"].split(" - ")[-1], "%s | %s | PART %s" % (s["d"], s["m"], s["pn"]), "", "ALL", "-", "Machine datasheet",
               slug="datasheet_" + mid)
    n = views(sh, w, h, d, 14, 12, 215, 150)
    sh.scale = "1:%d" % n
    # table
    rows = [("Model id", mid), ("Designation", s["d"]), ("Manufacturer", s["m"]), ("Part number", s["pn"]), ("Class / role", "%s / %s" % (s["cls"], ROLE[s["r"]])),
            ("Dimensions", "%d x %d x %d mm (W x H x D)" % tuple(s["dim"])), ("Mass (dry)", fkg(s["kg"])), ("Supply", s["v"])]
    if s["r"] == "g":
        rows.append(("Output", "%s (own load %s)" % (fw(s["gen"] * 1000), fw(s["w"][1]))))
    elif s["r"] == "s":
        rows.append(("Storage", "%.1f kWh, discharge %s" % (s["cap"], fw(s["gen"] * 1000))))
    elif s["r"] == "x":
        rows.append(("Converter rating", "%.0f kVA, losses %s" % (s["kva"], fw(s["w"][1]))))
    else:
        rows.append(("Power idle / typical / peak", "%s / %s / %s" % (fw(s["w"][0]), fw(s["w"][1]), fw(s["w"][2]))))
    rows += [("Heat dissipation", fw(s["heat"])), ("Unit price", fcr(s["cr"])), ("Lead time", "%d days" % s["lead"]),
             ("MTBF", ("{:,} h".format(s["mtbf"])) if s["mtbf"] else "n/a"), ("Maintenance interval", ("{:,} h".format(s["svc"])) if s["svc"] else "n/a"),
             ("Service life", "%d years" % s["life"]), ("Crew to operate", str(s["crew"])), ("Ingress protection", s["ip"]),
             ("Operating temperature", "%d to %d C" % (s["temp"][0], s["temp"][1])), ("Noise", ("%d dB(A)" % s["db"]) if s["db"] else "n/a"),
             ("Data interface", s["if"] or "none"), ("Software", ", ".join(s["sw"]) or "none")]
    sh.table(238, 18, [38, 133], rows, header=("PARAMETER", "VALUE"), rh=4.5, size=1.8, title="SPECIFICATION", bold_first=True)
    cy = 18 + 4.5 * (len(rows) + 1) + 6
    sh.text(238, cy, "CERTIFICATIONS", 2.0, bold=True)
    for i, c in enumerate(s["cert"]):
        sh.text(238, cy + 4.5 + i * 3.8, "- " + c, 1.7, maxw=170)
    cy2 = cy + 4.5 + len(s["cert"]) * 3.8 + 4
    sh.text(238, cy2, "NOTES", 2.0, bold=True)
    for i, ln in enumerate(wrap(s["n"], 78)[:6]):
        sh.text(238, cy2 + 4.5 + i * 3.8, ln, 1.7)
    # power profile
    py = 178
    sh.text(16, py, "ELECTRICAL PROFILE", 2.2, bold=True)
    if s["r"] in ("c", "x") and s["w"][2] > 0:
        mx = s["w"][2]
        for i, (lab, v) in enumerate((("Idle", s["w"][0]), ("Typical", s["w"][1]), ("Peak", s["w"][2]))):
            yy = py + 4 + i * 6.2
            sh.text(16, yy + 3.2, lab, 1.8)
            sh.rect(34, yy, max(100.0 * v / mx, 0.2), 4.2, "n", BAR)
            sh.text(36 + 100.0 * v / mx, yy + 3.2, fw(v), 1.7)
    elif s["r"] in ("g", "s"):
        sh.text(16, py + 7, "Producer / storage: %s" % (("output " + fw(s["gen"] * 1000)) if s["r"] == "g" else ("%.1f kWh, %s discharge" % (s["cap"], fw(s["gen"] * 1000)))), 2.0)
    else:
        sh.text(16, py + 7, "Passive item: no electrical load.", 2.0)
    # where used
    raw = ship.raw
    use = {}
    for r in raw["rooms"]:
        c = sum(1 for p in r["props"] if p["m"] == mid) + sum(1 for dr in raw.get("doors", []) if dr["m"] == mid and dr["a"] == r["id"])
        if c:
            use[r["name"]] = c
    ux = 16
    uy = py + 30
    sh.text(ux, uy, "INSTALLED IN THE SHIP", 2.2, bold=True)
    if use:
        sh.table(ux, uy + 3, [90, 20], sorted(use.items())[:12], header=("ROOM", "QTY"), rh=4.2, size=1.8, maxrows=12)
    else:
        sh.text(ux, uy + 6, "Not placed in the current layout (catalogue item).", 1.8, ital=True)
    return sh


def spec_sheets(ship):
    """All S sheets for the ship; [] when specs.json is not available."""
    specs, rt, deck, dept, tot = totals(ship)
    if not specs:
        return []
    out = [power_sld(ship, specs, rt, deck, dept, tot), bar_sheet(ship, specs, rt, deck, dept, tot)]
    k = 3
    for mid in HEROES:
        if mid in specs:
            out.append(datasheet(ship, specs, mid, "S-%02d" % k))
            k += 1
    return out
